<style  type="text/css"> 
cool {
  width: 100px;
  height: 100px;
  background-color: red;
  position: relative;
  -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
  -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
  -webkit-animation-iteration-count: infinite; /* Safari 4.0 - 8.0 */
  animation-name: example;
  animation-duration: 4s;
  animation-iteration-count: infinite;
}

/* Safari 4.0 - 8.0 */
@-webkit-keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}

/* Standard syntax */
@keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}
</style>

<b><center>
<span style="font-size: 24pt; line-height: 1.2">
COMS W4111: Introduction to Databases
</span>
</center></b>
</span><br>
<p>
<i><center>
<span style="font-size: 20pt; line-height: 1.2">
Lecture 1: Introduction and Overview
</span>
</center></i>

_Environment Setup:_ __Ignore for now.__ Wizard stuff.

In [1]:
import pymysql

%load_ext sql
%sql mysql+pymysql://dbuser:dbuserdbuser@localhost/w4111f19
%sql select * from students limit 5

db_cnx = pymysql.connect(host='localhost',
                             user='dbuser',
                             password='dbuserdbuser',
                             db='w4111f19',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

 * mysql+pymysql://dbuser:***@localhost/w4111f19
5 rows affected.

<u><span style="font-size: 24px;">Lecture Overview</span></u>

1. Introductory Material:
    - Course, sections and waitlist.
    - The course: course objectives, logistics, assignments/grading, material and outline, etc.<br><br>
1. Technical Topics - Introduction and Overview of:
    - Data, databases and database management systems.
    - SQL and the relational model.
    - Introduction to data modeling.<br><br>
1. Homework 1.

# Introduction

## Waitlist and Section

### Waitlist

- The administrative staff of the Dept. of Computer Science __directly__ manages enrollment in the sections and the wait lists.
    - COMS W4111 is __ALWAYS__ oversubscribed and has huge wait lists.
    - The course is a requirement for several majors and tracks.
    - There are __complex rules__ about prioritizing students for course enrollment, and also which students can take the hybrid section.
    
    
- The limiting factor on the standard, in-person lecture enrollment is the size of the room. We have to comply with university, city and state fire and safety codes.


- Summary: Contact Jessica Rosa in the Dept. of Computer Science if you want to discuss the waitlist or enrollment in sections. <span style="color:red;"><b>You must work with the CS department (Jessica Rosa) if you have special circumstances for waitlist prioritization.</b></span>

### Sections

- There are three identical sections for this course:
    1. 002: A conventional, in-person lecture format.
    2. H02: A "hybrid" section, in which students can watch the lecture live or access a recording.
    3. V02: [Columbia Video Network.](https://cvn.columbia.edu/)
    
    
- I have authorized all students to have access to the videos. H02 section students can attend lectures if there are open seats.


- The coursework, exams, assignments, TAs, ... are identical for all sections.


- __Note:__
    - We cannot accommodate all students who want to take W4111 due to room size constraints.
    - If you join this in-person section, there is another student that cannot take the class.
    - Every time I come to a lecture and see empty seats, I think of all the students who wanted to attend but we did not accommodate.
    - This makes me cranky.
    - Students who do not attend lectures will come to office hours and ask questions on topics that I covered in lecture. Students come to office hours and ask questions that I answered in class.
    - This makes crankier.
    - You do not want a cranky professor.
    - I periodically take attendance and assign extra credit to attendees or deduct points for absent students.
    - This makes me less cranky.

## The Course

### Description

From the [Columbia University Bulletin](http://bulletin.columbia.edu/columbia-college/departments-instruction/computer-science/#coursestext)

"The fundamentals of database design and application development using databases: entity-relationship modeling, logical design of relational databases, relational data definition and manipulation languages, SQL, query processing, transaction processing. <span style="color:red;"><b>Programming projects are required."</b></span> (Note: Emphasis added).


The CU course description lists the following prerequisites:
- _COMS W3137 -- Honors Data Structures and Algorithms_ or _W3134 -- Data Structures in Java_
- Fluency in Java
- Instructor's permission.

### Modification for this Section

- A course in data structures is helpful for __this__ section of W4111 __but not essential.__<br>
We will help you with any data structures knowledge you lack.



- Java is an excellent language for learning algorithms, data structures and programming fundamentals. __But, this section will use Python for examples, homework, etc.__ Python and the tool ecosystem are becoming the predominate language and tools for database centric scenarios.


- This section requires programming. Why?
    - Any non-trivial use of data and databases in any field requires programming. This is not Star Trek. You cannot shout, "Computer! Analyze ..."
    - You might think, "But, I do not want to program. I want to go into financial services, private equity, ... and become rich. I can just use tools like [Pandas.]" (https://pandas.pydata.org/)
    - "Wes McKinney started working on pandas in 2008 while at AQR Capital Management out of the need for a high performance, flexible tool to perform quantitative analysis on financial data."https://en.wikipedia.org/wiki/Pandas_(software)
    
    
- Many students dislike the experience but later find that it helped on interviews, internships, etc.

### Why Python

- The course description states Java. Why do you use Python?


- Python and the Python ecosystem are the dominant technology for working with data and databases.


| <img src="../../images/python_and_db.jpeg"> |
| :---: |
| Python and Databases |

| <a href="https://www.researchgate.net/figure/Schematic-view-of-the-Python-scientific-software-ecosystem-Figure-taken-from-Jake_fig1_332799309"><img src="https://www.researchgate.net/publication/332799309/figure/fig1/AS:753947908272130@1556766597837/Schematic-view-of-the-Python-scientific-software-ecosystem-Figure-taken-from-Jake.png" alt="Schematic view of the Python scientific software ecosystem. Figure taken from Jake VanderPlas's presentation at the PyCon 2017 conference [3]."/></a>|
| :---: |
| [Python Engineering and Data Ecosystem](https://www.researchgate.net/figure/Schematic-view-of-the-Python-scientific-software-ecosystem-Figure-taken-from-Jake_fig1_332799309) |

### Learning Curve

1. The learning curve can be steep at the beginning. This can and will be anxiety producing for some students.
<br><br>
2. We will get you over the hump of the curve and productive.
<br><br>
3. Many students, including non-CS, have found the skills useful in internships, job interviews, ...

### Instructors

#### The Professor

- Contact information:
    - Email: dff9@columbia.edu
    - Slack: https://dff-columbia.slack.com/


- Donald F. Ferguson
    - [Ansys, Inc.](https://www.ansys.com/): _Senior Technical Fellow, Chief Software Architect._
    - _Adjunct Professor,_ Dept. of Computer Science.
    

- Academic experience
    - Ph.D. in Computer Science, Columbia University, 1989.
    - Joined Columbia as full time _Professor of Professional Practice_, 01-Jan-2018.
    - Transitioned back to Adjunct Professor, 01-Jan-2019.
    - 11 semesters as an adjunct professor teaching
        - _E6998: Topics in Computer Science_ or _E6156: Topics in SW Engineering_
            - Cloud Computing
            - Web and Internet Application Development
            - Web Application Servers and Applications
            - Microservices
        - _W4111 - Introduction to Databases_
    - _Professor of Professional Practice in Computer Science,_ January 2018
         - _E1006 - Introduction to Computing for Engineers and Applied Scientists using Python_
         - _W4111 - Introduction to Databases_
         - _E6156 - Topics in SW Engineering: Microservices and Cloud Applications_

- 35 years industry experience
    - [IBM Fellow](https://en.wikipedia.org/wiki/IBM_Fellow), Chief Architect for [IBM Software Group](https://en.wikipedia.org/wiki/IBM_Software_Group_(SWG)
    - Microsoft Technical Fellow
    - Executive Vice President, Distinguished Engineer, Chief Technology Officer, [CA Technologies](https://www.ca.com/us.html)
    - Vice President, CTO, Senior Technical Fellow, [Dell Software Group](https://en.wikipedia.org/wiki/Dell_Software)
    - Co-Founder and CTO, [Seeka TV](https://seekatv.com/)
    - Senior Technical Fellow, Chief SW Architect, [Ansys, Inc.](http://www.ansys.com)


- Publications
    - Approximately 60 technical publications.
    - Authored, co-authored several standards in web applications and web services.
    - _Web Services Platform Architecture: SOAP, WSDL, WS-Policy, WS-Addressing, WS-BPEL, WS-Reliable Messaging, and More,_ ISBN-13: 978-0131488748, 2005, Pearson Education.
    - 12 patents.


- Personal and hobbies
    - Two amazing daughters (One is Barnard student. One is a senior in high school)
    - Interested in languages. Speak Spanish reasonably well and trying to learn Arabic.
    - Black Belt in Kenpo Karate
    - Amateur astronomy
    - Road bicycling
    - Officer in the New York Guard

| <img src="../../images/aboutme.jpeg" width="150%"> |
| :---: |
| __About Me__ |

#### Course/Instruction Assistants

We have great CAs/IAs. They will announce on Piazza.


- CA/IA from previous semesters:
    - TBD
    
    
- CA/IA who have taken the class from me.
    - TBD

### About this Course

- This course is foundational, and will teach you the core concepts in
    - Data modeling
    - Data model implementation; Data manipulation.
    - Different database models and database management systems.
    - Implementation of data centric applications and database management systems.
    
    
- ANY non-trivial application
    - Requires a well-designed data model.
    - Implements a data model and manipulates data.
    - Uses a database management system.
    
    
- Understanding databases and database management is core to the “hottest fields” in computer science, e.g.
    - Data science
    - Machine learning
    - Intelligent (Autonomous) systems
    - Internet-of-Things
    - Cybersecurity 
    - Cloud Computing
    
    
- Database, database application, etc. skills are increasingly central to many disciplines, including economics, IEOR, mechanical and electrical engineering, business and finance, ...
    
    
- University courses on databases sometimes focus on theory and abstract concepts. This course will cover theory, but the emphasis will be on:
    - Practical, hands-on applications of databases.
    - Developing and understanding database centric applications.
    - Patterns and best practices.
    
   
- <span style="color:red"> __Personal perspective__
    - A large percent of my career has been spent figuring out or leading teams that figured out how to model, implement and manipulate data.
    - I have used the information in this class more than anything else I have learned.
    - This will likely be true for you.
</span>

### Course Objectives

- Have fun, learn a lot and come to appreciate and enjoy some amazing technology.


- Provide a foundation that allows you to succeed in future courses. This is an _introduction_ to databases. The technology is crucial for
    - Advanced database classes
    - Machine learning
    - Big data, data analysis
    - Numerical, simulation and analytics in operations research, engineering, economics, finance, life sciences, etc.
    
    
- Enable you to successfully apply the technology in your work and profession.

<br>
<div class="cool" style="text-align:center;color:red;font-size:300%;line-height:1.2;">Have cool stuff to talk about on interviews and in your resumes.</div>
<br>

### Organization and Logistics

- Lecture: Friday, 10:10 AM-12:40 PM, Room 309 Havemeyer

 
- Instructor: Donald F. Ferguson (dff@cs.columbia.edu)


- Office Hours:
    - Fridays: 8:30 AM - 10:00 PM, 3:30 PM -? PM. 
    - By appointment, as needed, as available.
    - I hold a lot of extra office hours.
        - I typically post on Piazza when I will have extra availability.
        - The extra OHs may be "recitations," which are in-person and on-line, or just on-line.
        - Extra OH and recitations are often on the weekend or in the evening.
        - OH and recitations are sometime on-line meetings and I record them for CVN and Hybrid section students.
    
    
- Collaboration/Contact
    - The class is on [Piazza](https://piazza.com/class/jy3jm0i73f8584)
        - General questions
        - Clarification of homeworks, class material, etc.
    - Slack, for quick messages and questions.
        - Direct message to me, and
        - Please join slack and the channel [#w4111s19](https://join.slack.com/t/dff-columbia/shared_invite/enQtMjg0Mzk4MTQwMzQxLTMxYTY1YjJkOTQ1ZGY2ZjFhMGQzYTMzOWI5ZTBiYzY3YmQ1OTIzOGFkZDcwMDkyNzFiNWQ3M2NlYzM2YmU0ZTM) for quick questions/comments to class.

    - The course lectures, sample code, etc. will be on GitHub.
        - GitHub home page (https://donald-f-ferguson.github.io/w4111-Databases/)
        - Repository/Project (https://github.com/donald-f-ferguson/w4111-Databases)
    - Course Assistants: See above

### Assignments, Exams and Grades

- Point value of assignments and exams
    - 50%: Homework assignments
        - Approximately one HW every two weeks, for a total of 5.
        - Primarily programming projects.
    - Exams: All exams are "take home exams."
        - Mix of short programming assignments and questions.
        - 20% of grade is midterm exam score.
        - 30% is final exam score. 
    - Extra-credit: Class participation, contributions on Piazza and office hour participation, extra work on assignments, etc. earn extra-credit points.
    - Perfect score is an A. A+ requires extra credit.
       

- Late submission
    - You have a total of 5 grace days to apply for all homeworks.
    - 1 minute past the due date counts for 1 day. 24 hours + 1 minute counts for two days.
    - You cannot use grace days for midterm, final exam or extra-credit assignments.
    - NOTE:
        - Respect for the individual is paramount. 
        - We will always accommodate illness, family emergencies, etc.

### Environment and material
- Course material
    - Lectures and references: Textbooks are dated and also lack realistic scenarios and concepts.
    - Optional textbook:
        - _Database Management Systems, 3rd Edition_, Ramakrishnan and Gehrke, ISBN: 978-0072465631
        - We will cover a subset of the material in the textbook, and in a different order.
    - I will bring in examples from industry, engineering and practical experience.
    - Lecture material and examples:
        - Will be Jupyter Notebooks (http://jupyter.org/) for most lectures. I usually install the full [Anaconda suite.](https://www.anaconda.com/download)
        - Slides (PowerPoint) for some lectures.
        - Notebooks, slides, sample code, etc. will be available on [GitHub project](https://github.com/donald-f-ferguson/w4111-Databases) for the course. The easiest approach is to clone the project repository.
        
        
- Project and development
    - We will  use Python. 
    - Speak with me if you have a compelling reason for wanting to use a different programming language.
    
    
- Development environment
    - Database engines and tools
        - We will start with the relational data model. Please install the latest versions of
            - [MySQL](https://dev.mysql.com/downloads/mysql/)
            - [MySQL Workbench](https://dev.mysql.com/downloads/mysql/).
        - We will also use [Neo4j](https://neo4j.com/), [CouchDB](http://couchdb.apache.org/) and Redis (https://redis.io/), but you do not need to install now.
        - I will try to cover [DynamoDB](https://aws.amazon.com/dynamodb/), [DocumentDB](https://aws.amazon.com/documentdb/) and [Firebase Realtime Database](https://firebase.google.com/docs/database/), which are cloud DBs.
    - [Integrated Development Environments](https://en.wikipedia.org/wiki/Integrated_development_environment)
        - The [JetBrains](https://www.jetbrains.com/student/) tools are free for students, and useful for Python, JavaScript and Java. __I strongly recommend you use an IDE developing code.__ Install the __Professional Edition__ and get a free student license.
        - I will use Ananconda/Jupyter for most of the lectures and examples. You can choose to install
            - Install Python 3
            - [Anaconda Community Distribution](https://www.anaconda.com/distribution)
            - Ananconda includes the [Spyder](https://github.com/spyder-ide/spyder) and VisualStudio for Python. I __strongly__ prefer JetBrains but you can use Spyder.

<div class="cool" style="line-height:1.2;">
<b>My normal development approach is:</b>
<ul>
<li>Develop and test code using PyCharm (IDE)
<li>Copy into Notebook when "done.
<li>Debugging is very hard without a good IDE debugger.
</ul>
I suggest you do the same and use PyCharm.
</div>
     
     
In lectures, I will provide links to on-line material providing definitions and optional information. I often use Wikipedia because it is a good starting point and has many references.

### Course Outline

__Module I: Foundational Concepts__

1. Introduction to databases, role in applications, type of DB applications and overall system software architecture.

2. Information and data modeling and best practices, focusing on supporting application scenarios.

3. Relational data model (theory), Relational Database Management Systems, Structured Query Language, data query and update scenarios.

4. Extended topics in SQL and RDBMS (performance, security, constraints, triggers, connection management, etc).

__Module II: Database Management System Implementation/Architecture__

5. Storage management, disk management, buffer management, indexes.

6. Query processing and optimization:  Query evaluation, query parsing and parse trees, operator implementation algorithms, query rewrite, query optimization techniques.

7. Concurrency control and transaction management.

__Module III: NoSQL Database Overview__

8. Overview, graph databases, key-value databases, document databases.

9. Amazon S3, Amazon DynamoDB, Google Firebase/Cloud Firestore.

__Module IV: Decision Support, Data Analysis__

10. Overview of schema denormalization, OLAP cubes, data analytics, machine learning.

# Technical Topics

## Data, Databases, Data Models and Database Management Systems

### What is Data?

| <img src="../../images/Slide28.jpg" width="900px"> |
| :---: |
| __What is Data__ |

### Examples of Data

| <img src="../../images/Slide29.jpg" width="900px"> |
| :---: |
| __Examples__ |

### Some Ways to Think about Data

#### Structured vs Unstructured

| <img src="../../images/datastructure.jpg" width="900px"> |
| :--------: |
| __Structured vs Unstructured__ |

##### Structured Data

- High degree of organization.


- All records for a given type have
    - The same fields.
    - The fields are strongly typed.
    - There are _integrity constraints_ on values, e.g. __NOT NULL.__
    
    
- The _relational model_ is the canonical example.
    - The data is __structured,__ which means you must define the structure $\Rightarrow$ there is a __data definition language (DDL).__ A DDL is similar to defining a class in Java, C++ or Python.
    - Instances of data (rows, tuples) must match the DDL in the same way objects match the class definition.
    - The Relational Model has additional capabilities:
        - Integrity constraints, e.g. ```NOT NULL.``` _Primary Key_ means that the $student\_id$ is ```NOT NULL``` and ```UNIQUE.```
        - Referential Integrity:  For every _Grade_ row, there must be one row with a matching $student\_id$ in _Students._
        - Indexes: There is an auxiliary data structure that speeds up locating students using name fields.
        
        
- Some examples:

In [2]:
%sql select * from students limit 3

 * mysql+pymysql://dbuser:***@localhost/w4111f19
3 rows affected.

[('200266200', 'Ahmed', 'Abbad', 'alabba200@cs.uregina.ca'),
 ('200266202', 'Qaswar', 'Rai', 'ali202@cs.uregina.ca'),
 ('200266203', 'Nicholas', 'Phongsavath', 'phosan203@cs.uregina.ca')]

In [3]:
%sql select * from Grades where student_id='200266200' limit 3

 * mysql+pymysql://dbuser:***@localhost/w4111f19
3 rows affected.

[('200266200', 'CS100', 90.5),
 ('200266200', 'CS110', 85.0),
 ('200266200', 'CS210', 90.0)]

In [7]:
try:
    res = %sql insert into students (student_id, first_name, last_name) \
        values("2020", "Ferguson", "Donald")
except Exception as e:
    print("Insert failed with exception = ", e)
else:
    print("Insert returned res=", res)

 * mysql+pymysql://dbuser:***@localhost/w4111f19
Insert failed with exception =  (pymysql.err.InternalError) (1364, "Field 'email' doesn't have a default value")
[SQL: insert into students (student_id, first_name, last_name)          values("2020", "Ferguson", "Donald")]
(Background on this error at: http://sqlalche.me/e/2j85)

In [8]:
try:
    res = %sql insert into students (student_id, first_name, last_name, email, iq) \
        values("2020", "Ferguson", "Donald", "dff9@columbia.edu", 20)
except Exception as e:
    print("Insert failed with exception = ", e)
else:
    print("Insert returned res=", res)

 * mysql+pymysql://dbuser:***@localhost/w4111f19
Insert failed with exception =  (pymysql.err.InternalError) (1054, "Unknown column 'iq' in 'field list'")
[SQL: insert into students (student_id, first_name, last_name, email, iq)          values("2020", "Ferguson", "Donald", "dff9@columbia.edu", 20)]
(Background on this error at: http://sqlalche.me/e/2j85)

In [10]:
try:
    res = %sql insert into students (student_id, first_name, last_name, email) \
        values("2020", "Ferguson", "Donald", "dff9@columbia.edu")
except Exception as e:
    print("Insert failed with exception = ", e)
else:
    print("Insert the new row worked!")

 * mysql+pymysql://dbuser:***@localhost/w4111f19
1 rows affected.
Insert the new row worked!

In [11]:
try:
    res = %sql insert into students (student_id, first_name, last_name, email) \
        values("2020", "Smith", "Bubba", "bb1@columbia.edu")
except Exception as e:
    print("Insert failed with exception = ", e)
else:
    print("Insert the new row worked!")

 * mysql+pymysql://dbuser:***@localhost/w4111f19
Insert failed with exception =  (pymysql.err.IntegrityError) (1062, "Duplicate entry '2020' for key 'PRIMARY'")
[SQL: insert into students (student_id, first_name, last_name, email)          values("2020", "Smith", "Bubba", "bb1@columbia.edu")]
(Background on this error at: http://sqlalche.me/e/gkpj)

Stuctured data example:
- Fixed set of attributes (IQ not allowed)
- Contraints on values (email cannot be NULL)
- More sophisticated constraints: student_ID must be unique.

##### Semi-structured Data

- There are records with fields.


- You can parse the data to extract records and fields into data structures.


- Records may have some common fields, but any record may have any fields of any types.


- Documents are the canonical example:
    - There are common structural concepts: headers, lists, footnotes, etc.
    - But different documents have different combinations, nesting, etc.
    
    
- [CouchDB](http://couchdb.apache.org/) is an example of a document database. It stores semi-structured [JSON](https://www.json.org/) documents.

In [7]:
import json
import couchdb
svr = couchdb.Server("http://dbuser:dbuserdbuser@localhost:5984/")
db = svr["w4111f19"]
for d in db:
    print(json.dumps(db[d], indent=2))

{
  "_id": "2570e0b648805195a380643653000a04",
  "_rev": "1-10a780c8d7d72b6c9192c80c467a68cb",
  "last_name": "Ferguson",
  "first_name:": "Donald",
  "email": "dff9@columbia.edu"
}
{
  "_id": "2570e0b648805195a3806436530019c2",
  "_rev": "1-57df65cd528657a96071612f71ab79f2",
  "student_ID": "200266200",
  "last_name": "Ahmed",
  "first_name": "Abbad",
  "email": "alabba200@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653001e7a",
  "_rev": "1-78cb67c248672e3f285658825188f40d",
  "student_ID": "200266202",
  "last_name": "Qaswar",
  "first_name": "Rai",
  "email": "ali202@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653002a07",
  "_rev": "1-cf1025dfa9337b03cfbefda60ae7ec59",
  "student_ID": "200266203",
  "last_name": "Nicholas",
  "first_name": "Phongsavath",
  "email": "phosan203@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a3806436530037b6",
  "_rev": "1-f000ea46e37126c5e25d2cd2625abb27",
  "student_ID": "200266204",
  "last_name": "Nikki",
  "first_name": "Pawlowski",
  "email": "pawlow204@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653003fd4",
  "_rev": "1-2b379766913635cfd239ffc3c08deab0",
  "student_ID": "200266205",
  "last_name": "Nathan",
  "first_name": "Ellis",
  "email": "elli205@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653004035",
  "_rev": "1-f6553a16bbe8ba3035ae5dec6641ac96",
  "student_ID": "200266206",
  "last_name": "John",
  "first_name": "Erick",
  "email": "eric20j206@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653004c16",
  "_rev": "1-709cd5e7d2d6998549f4b0bb12638f64",
  "student_ID": "200266207",
  "last_name": "Jody-Lee",
  "first_name": "DerVelden",
  "email": "vanervj207@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a38064365300597e",
  "_rev": "1-4a0d682e603bd2159c645a6f31d2902e",
  "student_ID": "200266208",
  "last_name": "Sabrina ",
  "first_name": "Tram",
  "email": "tra200s208@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006537",
  "_rev": "1-b20e091b36aeada8a2ab9de8c88c904b",
  "student_ID": "200266209",
  "last_name": "Ke",
  "first_name": "Tao",
  "email": "taoke209@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006641",
  "_rev": "1-edbc1a42dd8addccba944c67a17b745e",
  "student_ID": "200266210",
  "last_name": "Yupeng",
  "first_name": "",
  "email": "x210@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006b7c",
  "_rev": "1-afe23e6cfa1c488c7233216df93a3354",
  "student_ID": "200266211",
  "last_name": "Chidinma",
  "first_name": "Ukabam",
  "email": "ukaba211@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006c37",
  "_rev": "1-1ba2c72ff4269aacd73931e71a37bc5b",
  "student_ID": "200266212",
  "last_name": "Mandeep",
  "first_name": "Ghotra",
  "email": "gho212@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006e66",
  "_rev": "1-b2d6f5b544ea86d95522f3af40d0e2c5",
  "student_ID": "2020",
  "last_name": "Ferguson",
  "first_name": "Donald",
  "email": "dff9@columbia.edu"
}
{
  "_id": "2570e0b648805195a3806436530085e4",
  "_rev": "1-294fc6affb1269bdc6bda89a0b3c30b5",
  "student_ID": "2021",
  "last_name": "Smith",
  "first_name": "Bubba"
}
{
  "_id": "2570e0b648805195a38064365300872d",
  "_rev": "1-d76361f27b1b27e13561b05ed10f32da",
  "student_ID": "2022",
  "last_name": "Baggins",
  "first_name": "Bilbo",
  "nationality": "Shire"
}

In [8]:
new_p = { 'student_ID': '2022', 'last_name': 'Smith', 'first_name': 'Bubba'}
doc_id, doc_rev = db.save(new_p)
print("Doc ID = ", doc_id)

Doc ID =  e74436d05a2174437fee2a6c3f000968

In [9]:
dd = db[doc_id]
print(dd)

<Document 'e74436d05a2174437fee2a6c3f000968'@'1-e5e282e4d248bf593c48ce9264d550ad' {'student_ID': '2022', 'last_name': 'Smith', 'first_name': 'Bubba'}>

- That was straightforward and seems similar to relational.


- I can, however, add a document to the same DB/table but with different fields.

In [10]:
new_p = { 'student_ID': '202233', 'last_name': 'Baggins', 'first_name': 'Bilbo', 'nationality': 'Shire'}
doc_id, doc_rev = db.save(new_p)
print("Doc ID = ", doc_id)

Doc ID =  e74436d05a2174437fee2a6c3f000cac

In [11]:
dd = db[doc_id]
print(dd)

<Document 'e74436d05a2174437fee2a6c3f000cac'@'1-e7b9aaa8c6db62785ac20edc2676661c' {'student_ID': '202233', 'last_name': 'Baggins', 'first_name': 'Bilbo', 'nationality': 'Shire'}>

In [12]:
import json
svr = couchdb.Server("http://dbuser:dbuserdbuser@localhost:5984/")
db = svr["w4111f19"]
for d in db:
    print(json.dumps(db[d], indent=2))

{
  "_id": "2570e0b648805195a380643653000a04",
  "_rev": "1-10a780c8d7d72b6c9192c80c467a68cb",
  "last_name": "Ferguson",
  "first_name:": "Donald",
  "email": "dff9@columbia.edu"
}
{
  "_id": "2570e0b648805195a3806436530019c2",
  "_rev": "1-57df65cd528657a96071612f71ab79f2",
  "student_ID": "200266200",
  "last_name": "Ahmed",
  "first_name": "Abbad",
  "email": "alabba200@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653001e7a",
  "_rev": "1-78cb67c248672e3f285658825188f40d",
  "student_ID": "200266202",
  "last_name": "Qaswar",
  "first_name": "Rai",
  "email": "ali202@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653002a07",
  "_rev": "1-cf1025dfa9337b03cfbefda60ae7ec59",
  "student_ID": "200266203",
  "last_name": "Nicholas",
  "first_name": "Phongsavath",
  "email": "phosan203@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a3806436530037b6",
  "_rev": "1-f000ea46e37126c5e25d2cd2625abb27",
  "student_ID": "200266204",
  "last_name": "Nikki",
  "first_name": "Pawlowski",
  "email": "pawlow204@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653003fd4",
  "_rev": "1-2b379766913635cfd239ffc3c08deab0",
  "student_ID": "200266205",
  "last_name": "Nathan",
  "first_name": "Ellis",
  "email": "elli205@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653004035",
  "_rev": "1-f6553a16bbe8ba3035ae5dec6641ac96",
  "student_ID": "200266206",
  "last_name": "John",
  "first_name": "Erick",
  "email": "eric20j206@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653004c16",
  "_rev": "1-709cd5e7d2d6998549f4b0bb12638f64",
  "student_ID": "200266207",
  "last_name": "Jody-Lee",
  "first_name": "DerVelden",
  "email": "vanervj207@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a38064365300597e",
  "_rev": "1-4a0d682e603bd2159c645a6f31d2902e",
  "student_ID": "200266208",
  "last_name": "Sabrina ",
  "first_name": "Tram",
  "email": "tra200s208@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006537",
  "_rev": "1-b20e091b36aeada8a2ab9de8c88c904b",
  "student_ID": "200266209",
  "last_name": "Ke",
  "first_name": "Tao",
  "email": "taoke209@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006641",
  "_rev": "1-edbc1a42dd8addccba944c67a17b745e",
  "student_ID": "200266210",
  "last_name": "Yupeng",
  "first_name": "",
  "email": "x210@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006b7c",
  "_rev": "1-afe23e6cfa1c488c7233216df93a3354",
  "student_ID": "200266211",
  "last_name": "Chidinma",
  "first_name": "Ukabam",
  "email": "ukaba211@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006c37",
  "_rev": "1-1ba2c72ff4269aacd73931e71a37bc5b",
  "student_ID": "200266212",
  "last_name": "Mandeep",
  "first_name": "Ghotra",
  "email": "gho212@cs.uregina.ca"
}
{
  "_id": "2570e0b648805195a380643653006e66",
  "_rev": "1-b2d6f5b544ea86d95522f3af40d0e2c5",
  "student_ID": "2020",
  "last_name": "Ferguson",
  "first_name": "Donald",
  "email": "dff9@columbia.edu"
}
{
  "_id": "2570e0b648805195a3806436530085e4",
  "_rev": "1-294fc6affb1269bdc6bda89a0b3c30b5",
  "student_ID": "2021",
  "last_name": "Smith",
  "first_name": "Bubba"
}
{
  "_id": "2570e0b648805195a38064365300872d",
  "_rev": "1-d76361f27b1b27e13561b05ed10f32da",
  "student_ID": "2022",
  "last_name": "Baggins",
  "first_name": "Bilbo",
  "nationality": "Shire"
}
{
  "_id": "e74436d05a2174437fee2a6c3f000968",
  "_rev": "1-e5e282e4d248bf593c48ce9264d550ad",
  "student_ID": "2022",
  "last_name": "Smith",
  "first_name": "Bubba"
}
{
  "_id": "e74436d05a2174437fee2a6c3f000cac",
  "_rev": "1-e7b9aaa8c6db62785ac20edc2676661c",
  "student_ID": "202233",
  "last_name": "Baggins",
  "first_name": "Bilbo",
  "nationality": "Shire"
}

- There is a basic structure.


- The list of attributes and the values are flexible.


- Application logic implements more functionality, like data correctness.


- The documents you insert effectively defines the schema.

##### Unstructured

- No explicit records or delimiters. No fields. No properties.


- Just a sequence of characters/bytes that can be interpreted by some processing engine.


- Images, audio files, etc. are examples.

In [25]:
import codecs

db = "C:\\Users\\dferguso\\OneDrive - ANSYS, Inc\\Columbia\\W4111f19\\w4111-Databases\\images\\"
fn = db + "Columbia_University_logo.jpg"

image_data =  open(fn, "rb")
image_data = image_data.read(100)
image_data

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xe1\x10\xfaExif\x00\x00MM\x00*\x00\x00\x00\x08\x00\x04\x01;\x00\x02\x00\x00\x00\x10\x00\x00\x08J\x87i\x00\x04\x00\x00\x00\x01\x00\x00\x08Z\x9c\x9d\x00\x01\x00\x00\x00 \x00\x00\x10\xd2\xea\x1c\x00\x07\x00\x00\x08\x0c\x00\x00\x00>\x00\x00\x00\x00\x1c\xea\x00\x00\x00\x08\x00\x00'

| <img src="../../images/image_file_data.jpg"> |
| :---: |
| __Unstructured Data__ |

##### Course Focus

- We will focus on structured data and some on semi-structured. 


- Need to constrain the scope for a one semester class.


- Structured data concepts are foundational and apply to semi-structured and unstructured data.


- Unstructured data scenarios often require extracting or extending with structured data.

#### [Data versus Metadata](https://en.wikipedia.org/wiki/Metadata)

##### Concept

- Metadata is "data information that provides information about other data". Three distinct types of metadata exist:
    1. Descriptive metadata
    2. Structural metadata
    3. Administrative metadata.
    
    
- Descriptive metadata describes a resource for purposes such as discovery and identification. It can include elements such as title, abstract, author, and keywords.


- Structural metadata is metadata about containers of data and indicates how compound objects are put together, for example, how pages are ordered to form chapters. It describes the types, versions, relationships and other characteristics of digital materials.


- Administrative metadata provides information to help manage a resource, such as when and how it was created, file type and other technical information, and who can access it.


- We will cover metadata, especially while studying relational data.

##### Examples

<u>Tell me about a Student</u>

In [26]:
%sql select * from students where student_ID="2020"

 * mysql+pymysql://dbuser:***@localhost/w4111f19
1 rows affected.

[('2020', 'Ferguson', 'Donald', 'dff9@columbia.edu')]

<u>Describe what information you have about ```people.```</u>

In [27]:
%sql describe students

 * mysql+pymysql://dbuser:***@localhost/w4111f19
4 rows affected.

[('student_ID', 'varchar(30)', 'NO', 'PRI', None, ''),
 ('first_name', 'varchar(30)', 'NO', '', None, ''),
 ('last_name', 'varchar(30)', 'NO', '', None, ''),
 ('email', 'varchar(100)', 'NO', 'UNI', None, '')]

- Programming languages have similar concepts.
    - [Java Reflection]() is an example.
    - Python has a similar concept. (https://www.geeksforgeeks.org/reflection-in-python/)
    
    
| <img src="../../images/java_reflection.jpeg"> |
| :---: |
| [Java Reflection](https://www.geeksforgeeks.org/reflection-in-java/)

__Python:__

In [5]:
import json
def whatDidIGet(huh):
    print("What the heck did you pass me?")
    print("The type is = ", type(huh))
    print("The methods and properties are: ", json.dumps(dir(huh), indent=2))

In [6]:
# Create a simple list.
x = [1, 2, 3]

whatDidIGet(x)

What the heck did you pass me?
The type is =  <class 'list'>
The methods and properties are:  [
  "__add__",
  "__class__",
  "__contains__",
  "__delattr__",
  "__delitem__",
  "__dir__",
  "__doc__",
  "__eq__",
  "__format__",
  "__ge__",
  "__getattribute__",
  "__getitem__",
  "__gt__",
  "__hash__",
  "__iadd__",
  "__imul__",
  "__init__",
  "__init_subclass__",
  "__iter__",
  "__le__",
  "__len__",
  "__lt__",
  "__mul__",
  "__ne__",
  "__new__",
  "__reduce__",
  "__reduce_ex__",
  "__repr__",
  "__reversed__",
  "__rmul__",
  "__setattr__",
  "__setitem__",
  "__sizeof__",
  "__str__",
  "__subclasshook__",
  "append",
  "clear",
  "copy",
  "count",
  "extend",
  "index",
  "insert",
  "pop",
  "remove",
  "reverse",
  "sort"
]

In [7]:
type(getattr(x, "sort"))

builtin_function_or_method

In [8]:
dir(getattr(x, "sort"))

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [9]:
# Create a simple list.
def someFunction(y):
    pass

whatDidIGet(someFunction)

What the heck did you pass me?
The type is =  <class 'function'>
The methods and properties are:  [
  "__annotations__",
  "__call__",
  "__class__",
  "__closure__",
  "__code__",
  "__defaults__",
  "__delattr__",
  "__dict__",
  "__dir__",
  "__doc__",
  "__eq__",
  "__format__",
  "__ge__",
  "__get__",
  "__getattribute__",
  "__globals__",
  "__gt__",
  "__hash__",
  "__init__",
  "__init_subclass__",
  "__kwdefaults__",
  "__le__",
  "__lt__",
  "__module__",
  "__name__",
  "__ne__",
  "__new__",
  "__qualname__",
  "__reduce__",
  "__reduce_ex__",
  "__repr__",
  "__setattr__",
  "__sizeof__",
  "__str__",
  "__subclasshook__"
]

### Data Explosion


| <img src="../../images/datasize.png">|
| :---: |
| __Data Explosion__ |

- The world's total, yearly data creation will reach [163 zettabytes in 2025.](https://www.forbes.com/sites/andrewcave/2017/04/13/what-will-we-do-when-the-worlds-data-hits-163-zettabytes-in-2025/#43b56b37349a)


- __DANGER:__ Math before caffeine.


- Zettabyte is $1000^7 = 10^{21}.$ 


- World's population is/will be approximately $10 * 10^{9} = 10^{10}$


- Data per person in 2025 = <br><br>
\begin{equation}
\frac{1.63 * 10^2 * 10^{21}}{10^{10}} = \frac{1.63 * 10^{23}}{10^{10}} = 1.63 * 10^{13} = 16.3*10^{12} = 16.3*10^{3}*10^{9} = 16,000\ GB \ per \ person, \ per \ year.
\end{equation}


- In 2025, "an average connected person anywhere in the world will interact with connected devices nearly 4,800 times per day – one interaction every 18 seconds." [Forbes](https://www.forbes.com/sites/andrewcave/2017/04/13/what-will-we-do-when-the-worlds-data-hits-163-zettabytes-in-2025/#43b56b37349a). Each interaction creates new data.

### The Four Vs


| <img src="../../images/forvs.jpg" width="900px"> |
| :---: |
| __Four Vs of Data__ |

Some driving factors:
- Volume:
    - File/instance size: videos, images, VR, ...
    - Sources: Internet-of-Things, events and monitoring, ...
    
    
- Velocity:
    - Monitoring and events from everything.
    - Video and audio from everywhere.
    

- Veracity:
    - Measurement error and approximation.
    - Incorrect configuration, entry, processing applications.
    
    
- Variety:
    - Base types: several base models for structured data.
    - Every device emits its own event format.
    - Multiple encodings and formats of text (mail, web page, tweet) audio, video, ...

### Or, Maybe Five Vs

| <img src="../../images/fives.jpg" width="800px"> |
| :---: |
| Five Vs |

- Value: "It's like trying to find a needle in a haystack size pile of needles."

### Big data landscape

| <img src="../../images/landscape.png" width="900px"> |
| :---: |
| [Big Data Landscape](http://mattturck.com/bigdata2018/) |

### Databases

#### Definitions

“A database is an organized collection of data. It is the collection of schemas, tables, queries, reports, views, and other objects. The data are typically organized to model aspects of reality in a way that supports processes requiring information, such as modelling the availability of rooms in hotels in a way that supports finding a hotel with vacancies. (https://en.wikipedia.org/wiki/Database)”

“Systematically organized or structured repository of indexed information (usually as a group of linked data files) that allows easy retrieval, updating, analysis, and output of data. Stored usually in a computer, this data could be in the form of graphics, reports, scripts, tables, text, etc., representing almost every kind of information. Most computer applications (including antivirus software, spreadsheets, word-processors) are databases at their core.” (http://www.businessdictionary.com/definition/database.html)

#### Simplistic example

| <img src="../../images/northwind-model.jpg" width="900px"> |
| :---: |
| __Simplistic Example \(and First Datamodel\)__|

- Entity – Data about a “Thing,” e.g.
    - Person
    - Web click
    - Product
    
    
- Fields (Properties) – The data describing, defining an entity. Often named and typed, e.g.
    - (Height, Integer)
    - (Last name, String)
    
    
- Entity Set/Collection/Table
    - A group of things.
    - Usually the same ”kind of entity”
    
    
- Relationships/Associations – Links between entities, which convey semantic information, e.g.
    - Don IsA Professor
    - Don Teaches {COMS4111, COMSE6998)
    
    
    
#### Slightly Less Simplistic Example

| <img src="../../images/lessimple.jpg" width="900px"> |
| :---: |
| __Slightly Less Simplistic Schema__ |
<br>
<hr>
<br>


| <img src="../../images/less-simplistic.png" width="900px"> |
| :---: |
| __Slightly, Slightly Less Simplistic Schema__ |


- All joking aside. A single database/datamodel can have
    - 100s of entities.
    - 100s of relationships
    - 1000s of attributes.

### Database Management Systems

#### Concept


<img src="../../images/Slide52.jpg" width="90%">
<hr>
<img src="../../images/Slide53.jpg" width="90%">
<hr>
<br>

#### Types of Database Management Systems

- There are many, many, many different kinds of database management systems. The differences are:
    - Type of data: tables, documents, images, complex design models, ...
    - Use case optimizations: ready only/query, business transactions, realtime data sharing, ...
    - Deployment scenarios: mobile device, application embedded, high-performance cloud, ...
    
    
- We will go through a few representative databases in this course.



| <img src="../../images/coms4111-slides-90.jpg"> |
| :---: |
| __DBMS Taxonomy__ |

- We will cover the DBMS implementation in Module II. That is, what is the architecture and implementation of the DBMS SW.


- To understand DBMS models and usage, we will primarily focus on 4 database management systems:
    1. Relational (MySQL)
    1. Graph Database (Neo4J)
    1. Key/Value- data structure store (Redis)
    1. Document (CouchDB)


- Motivation:
    - https://db-engines.com/en/ranking adoption and growth.
    - Diversity of base models covers core patterns in _functionality_ and _performance._
    
| <img src="../../images/dbtype-percentage.jpeg"> |
| :---: |
| [DBMS popularity broken down by database model](https://db-engines.com/en/ranking_categories) |


| <img src="../../images/dbgrowth.jpeg"> |
| :---: |
| [Popularity changes per category, August 2018](https://db-engines.com/en/ranking_categories) |

- Why start with MySQL? Popular, open source and free.

| <img src="../../images/rdbranking.jpeg"> |
| :---: |
| [DB-Engines Ranking of Relational DBMS](https://db-engines.com/en/ranking/relational+dbms) |

#### DBMS Functions

<hr style="height:1px;">

| <img src="../../images/dbms-engine.jpg" width="600px"> |
| :---: |
| __DBMS Engine Overview__ |

<hr style="height:1px;">

A database management system is a large SW program that implements of set of functions. Thinking of the functions as a set of collaborating sub-modules/programs is one way to think about the DBMS. The modules are:


- _Query Compiler:_
    - Users and programs submit queries in a high-level format.
    - The query compiler processes the statement and converts into a set of actions.
    - Similar to compiling a SW program.
    

- _DDL Compiler:_ Similar to query compiler, but for statements that create and modify schema.


- _Execution Engine:_ "Runs" the generated code/plans produced by the various compilers.


- _Transaction Manager:_
    - Component that "manages" start, stop and coordination of "transactions." What is a "transaction?"
    - "In a Database Management System, a _transaction_ is a single unit of logic or work, sometimes made up of multiple operations. Any logical calculation done in a consistent mode in a database is known as a transaction. One example is a transfer from one bank account to another: the complete transaction requires subtracting the amount to be transferred from one account and adding that same amount to the other."


- _Logging and Recovery:_ Supports transaction processing and ensures data availability and consistency in the face of failures.


- _Concurrency Control:_
    - DBMS instances simultaneously execute many requests from many programs and users.
    - Prevents simultaneous database queries from interfering with each other.


- _Index/File/Record Manager:_ Uses auxiliary data structures (search trees, hashes, ...) to optimize finding information.


- _Buffer Manager:_ Manages allocation of RAM to database data to optimize access.


- _Storage Manager:_ Controls and manages the placement of database information of disks, tape, etc.

#### DBMS Software Structure

<hr style="height:1px;">

| <img src="../../images/db_sw_configuration.jpg" width="900px"> |
| :---: |
| __DBMS SW Structure__ |

<hr style="height:1px;">

- A database management system is a software programming running on a computer.


- Programs execute in an _operating system process._ (https://en.wikipedia.org/wiki/Process_(computing))


- What processes are executing on my laptop?

In [13]:
!tasklist /V

Image Name                     PID Session Name        Session#    Mem Usage Status          User Name                                              CPU Time Window Title
========================= ======== ================ =========== ============ =============== ================================================== ============ ========================================================================
System Idle Process              0 Services                   0          8 K Unknown         NT AUTHORITY\SYSTEM                                   972:34:17 N/A
System                           4 Services                   0     10,752 K Unknown         N/A                                                    15:20:51 N/A
Registry                       120 Services                   0     15,444 K Unknown         N/A                                                     0:02:11 N/A
smss.exe                       592 Services                   0        292 K Unknown         N/A                                                     0:00:00 N/A
csrss.exe                      908 Services                   0      2,352 K Unknown         N/A                                                     0:03:36 N/A
wininit.exe                   1004 Services                   0        704 K Unknown         N/A                                                     0:00:00 N/A
csrss.exe                     1016 Console                    1      3,516 K Running         N/A                                                     0:18:41 N/A
services.exe                   472 Services                   0      8,808 K Unknown         N/A                                                     5:09:29 N/A
lsass.exe                      628 Services                   0     53,556 K Unknown         N/A                                                     0:31:59 N/A
winlogon.exe                   884 Console                    1     20,472 K Unknown         N/A                                                     0:00:09 N/A
svchost.exe                   1076 Services                   0      9,796 K Unknown         N/A                                                     0:00:00 N/A
svchost.exe                   1100 Services                   0     65,008 K Unknown         N/A                                                     0:12:06 N/A
WUDFHost.exe                  1124 Services                   0      2,532 K Unknown         N/A                                                     0:00:03 N/A
fontdrvhost.exe               1148 Console                    1      6,096 K Unknown         N/A                                                     0:00:13 N/A
fontdrvhost.exe               1156 Services                   0        760 K Unknown         N/A                                                     0:00:00 N/A
svchost.exe                   1284 Services                   0     34,200 K Unknown         N/A                                                     0:24:16 N/A
WUDFHost.exe                  1336 Services                   0      3,508 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   1364 Services                   0     19,168 K Unknown         N/A                                                     0:01:30 N/A
dwm.exe                       1520 Console                    1     57,900 K Running         N/A                                                     3:12:58 DWM Notification Window
svchost.exe                   1568 Services                   0     16,540 K Unknown         N/A                                                     0:00:15 N/A
svchost.exe                   1576 Services                   0     38,084 K Unknown         N/A                                                     0:01:02 N/A
svchost.exe                   1688 Services                   0     15,068 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   1696 Services                   0     22,912 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   1704 Services                   0     16,380 K Unknown         N/A                                                     0:00:34 N/A
svchost.exe                   1732 Services                   0     20,484 K Unknown         N/A                                                     0:03:51 N/A
svchost.exe                   1800 Services                   0     20,588 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   1856 Services                   0     23,224 K Unknown         N/A                                                     0:00:05 N/A
svchost.exe                   1912 Services                   0     15,892 K Unknown         N/A                                                     0:09:33 N/A
svchost.exe                   1928 Services                   0     39,776 K Unknown         N/A                                                     0:01:41 N/A
svchost.exe                   1952 Services                   0    135,028 K Unknown         N/A                                                     1:47:13 N/A
svchost.exe                   2020 Services                   0     18,536 K Unknown         N/A                                                     0:10:20 N/A
svchost.exe                   1360 Services                   0     17,580 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2080 Services                   0     16,896 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2088 Services                   0     17,768 K Unknown         N/A                                                     0:00:06 N/A
svchost.exe                   2208 Services                   0     19,160 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2284 Services                   0     19,988 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2336 Services                   0     25,864 K Unknown         N/A                                                     0:13:23 N/A
svchost.exe                   2364 Services                   0     15,464 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2416 Services                   0     20,572 K Unknown         N/A                                                     0:00:05 N/A
svchost.exe                   2488 Services                   0     22,180 K Unknown         N/A                                                     0:00:04 N/A
svchost.exe                   2504 Services                   0     37,820 K Unknown         N/A                                                     0:00:02 N/A
igfxCUIService.exe            2716 Services                   0      2,260 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   2776 Services                   0     22,684 K Unknown         N/A                                                     0:16:21 N/A
svchost.exe                   2868 Services                   0     20,408 K Unknown         N/A                                                     0:00:37 N/A
svchost.exe                   2876 Services                   0     16,708 K Unknown         N/A                                                     0:00:04 N/A
svchost.exe                   2984 Services                   0     18,396 K Unknown         N/A                                                     0:00:19 N/A
WUDFHost.exe                  3048 Services                   0      2,192 K Unknown         N/A                                                     0:00:00 N/A
dasHost.exe                   3064 Services                   0      9,276 K Unknown         N/A                                                     0:00:38 N/A
UshUpgradeService.exe          896 Services                   0      1,596 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   3128 Services                   0     21,988 K Unknown         N/A                                                     0:03:30 N/A
Parity.exe                    3168 Services                   0    134,052 K Unknown         N/A                                                     5:30:10 N/A
svchost.exe                   3208 Services                   0     34,156 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   3412 Services                   0     17,532 K Unknown         N/A                                                     0:01:49 N/A
svchost.exe                   3444 Services                   0     43,620 K Unknown         N/A                                                     2:31:24 N/A
svchost.exe                   3460 Services                   0     17,220 K Unknown         N/A                                                     0:00:32 N/A
svchost.exe                   3508 Services                   0     19,044 K Unknown         N/A                                                     0:00:11 N/A
svchost.exe                   3580 Services                   0     22,208 K Unknown         N/A                                                     0:00:19 N/A
svchost.exe                   3760 Services                   0     30,436 K Unknown         N/A                                                     0:00:12 N/A
svchost.exe                   3988 Services                   0     24,956 K Unknown         N/A                                                     0:23:01 N/A
svchost.exe                   3996 Services                   0     17,596 K Unknown         N/A                                                     0:00:07 N/A
svchost.exe                   4004 Services                   0     14,756 K Unknown         N/A                                                     0:01:30 N/A
svchost.exe                   4088 Services                   0     18,848 K Unknown         N/A                                                     0:01:57 N/A
Memory Compression            2864 Services                   0  1,357,788 K Unknown         N/A                                                     0:28:57 N/A
WmiPrvSE.exe                  4144 Services                   0     33,512 K Unknown         N/A                                                     5:19:48 N/A
svchost.exe                   4212 Services                   0     27,572 K Unknown         N/A                                                     0:05:27 N/A
svchost.exe                   4272 Services                   0     22,988 K Unknown         N/A                                                     0:01:32 N/A
RtkAudioService64.exe         4372 Services                   0      1,848 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   4488 Services                   0     14,392 K Unknown         N/A                                                     0:00:03 N/A
svchost.exe                   4560 Services                   0     27,636 K Unknown         N/A                                                     0:00:05 N/A
svchost.exe                   4648 Services                   0     46,840 K Unknown         N/A                                                     0:01:23 N/A
RAVBg64.exe                   4692 Console                    1      3,260 K Running         N/A                                                     0:00:10 Realtek HD Audio Background Process for Vista
RAVBg64.exe                   4716 Console                    1      4,156 K Running         N/A                                                     0:00:14 Realtek HD Audio Background Process for Vista
svchost.exe                   4728 Services                   0     38,876 K Unknown         N/A                                                     0:00:04 N/A
spoolsv.exe                   4800 Services                   0     38,168 K Unknown         N/A                                                     0:00:38 N/A
unsecapp.exe                  4844 Console                    1      2,396 K Running         N/A                                                     0:00:01 OleMainThreadWndName
HostStorageService.exe        4884 Services                   0      1,096 K Unknown         N/A                                                     0:00:01 N/A
HostControlService.exe        4892 Services                   0      1,068 K Unknown         N/A                                                     0:00:01 N/A
HidMonitorSvc.exe             4976 Services                   0      2,296 K Unknown         N/A                                                     0:00:03 N/A
cb.exe                        5004 Services                   0     53,380 K Unknown         N/A                                                     1:46:58 N/A
tomcat9.exe                   5012 Services                   0     10,752 K Unknown         N/A                                                     0:07:39 N/A
IntelCpHDCPSvc.exe            5020 Services                   0      1,112 K Unknown         N/A                                                     0:00:00 N/A
svchost.exe                   5028 Services                   0     45,364 K Unknown         N/A                                                     0:03:32 N/A
EvtEng.exe                    5036 Services                   0      4,648 K Unknown         N/A                                                     0:00:07 N/A
esif_uf.exe                   5044 Services                   0        984 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   5060 Services                   0     28,796 K Unknown         N/A                                                     0:00:59 N/A
EPWD.exe                      5068 Services                   0      2,412 K Unknown         N/A                                                     0:28:27 N/A
svchost.exe                   5084 Services                   0     76,780 K Unknown         N/A                                                     0:11:35 N/A
QosServM.exe                  5096 Services                   0      2,092 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   5104 Services                   0     18,160 K Unknown         N/A                                                     0:00:09 N/A
ir_agent.exe                  5112 Services                   0      8,848 K Unknown         N/A                                                     0:00:34 N/A
macmnsvc.exe                  3560 Services                   0      3,652 K Unknown         N/A                                                     0:00:18 N/A
masvc.exe                     2928 Services                   0     15,408 K Unknown         N/A                                                     0:04:50 N/A
AgentService.exe              4684 Services                   0      1,780 K Unknown         N/A                                                     0:00:03 N/A
mfemms.exe                    5184 Services                   0      6,912 K Unknown         N/A                                                     0:00:43 N/A
SchedulerService.exe          5208 Services                   0      1,616 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   5312 Services                   0     15,244 K Unknown         N/A                                                     0:00:01 N/A
conhost.exe                   5368 Services                   0        708 K Unknown         N/A                                                     0:00:00 N/A
RegSrvc.exe                   5376 Services                   0      1,348 K Unknown         N/A                                                     0:00:01 N/A
SecurityHealthService.exe     5400 Services                   0      7,280 K Unknown         N/A                                                     0:00:04 N/A
svchost.exe                   5412 Services                   0     27,700 K Unknown         N/A                                                     0:00:45 N/A
sqlwriter.exe                 5440 Services                   0      1,524 K Unknown         N/A                                                     0:00:01 N/A
TracSrvWrapper.exe            5480 Services                   0      6,440 K Unknown         N/A                                                     0:26:23 N/A
svchost.exe                   5504 Services                   0     12,936 K Unknown         N/A                                                     0:00:01 N/A
WavesSysSvc64.exe             5560 Services                   0      2,024 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   5624 Services                   0     34,612 K Unknown         N/A                                                     0:00:21 N/A
svchost.exe                   5652 Services                   0     46,124 K Unknown         N/A                                                     0:00:11 N/A
ZeroConfigService.exe         5668 Services                   0      5,308 K Unknown         N/A                                                     0:00:27 N/A
svchost.exe                   5712 Services                   0     36,496 K Unknown         N/A                                                     0:09:28 N/A
svchost.exe                   5980 Services                   0     21,848 K Unknown         N/A                                                     0:00:10 N/A
svchost.exe                   6388 Services                   0     82,980 K Unknown         N/A                                                     0:05:39 N/A
conhost.exe                   6576 Services                   0        976 K Unknown         N/A                                                     0:00:02 N/A
svchost.exe                   6584 Services                   0     13,720 K Unknown         N/A                                                     0:00:01 N/A
svchost.exe                   6976 Services                   0     45,156 K Unknown         N/A                                                     0:00:21 N/A
IntelCpHeciSvc.exe            7272 Services                   0      1,104 K Unknown         N/A                                                     0:00:01 N/A
unsecapp.exe                  7640 Services                   0      2,488 K Unknown         N/A                                                     0:00:08 N/A
macompatsvc.exe               7900 Services                   0     11,096 K Unknown         N/A                                                     0:13:27 N/A
mfevtps.exe                   7936 Services                   0     15,088 K Unknown         N/A                                                     0:33:51 N/A
mfemactl.exe                  8132 Services                   0      3,448 K Unknown         N/A                                                     0:01:17 N/A
svchost.exe                   4624 Services                   0     18,176 K Unknown         N/A                                                     0:03:39 N/A
mcshield.exe                  5592 Services                   0    265,812 K Unknown         N/A                                                    24:00:58 N/A

- That is a little hard to read.


- Let's write some code to get as data.

In [14]:
import psutil
import copy
proc_list = []
for proc in psutil.process_iter():
    o = proc.as_dict(attrs=['pid', 'name', 'username', 'cpu_percent', 'memory_percent'])
    p_info = {}
    p_info['pid']=o['pid']
    p_info['username']=o['username']
    p_info['name']=o['name']
    p_info['cpu_percent']=o['cpu_percent']
    p_info['memory_percent']=round(o['memory_percent'],3)
    proc_list.append(p_info)

- Let's use a common data analysis tool to look at it.

In [15]:
import pandas

df = pandas.DataFrame(proc_list)

In [16]:
df

,cpu_percent,memory_percent,name,pid,username
0,0.0,0.000,System Idle Process,0,NT AUTHORITY\SYSTEM
1,0.0,0.064,System,4,NT AUTHORITY\SYSTEM
2,0.0,0.098,Registry,120,None
3,0.0,0.014,git-bash.exe,468,ANSYS\dferguso
4,0.0,0.053,services.exe,472,None
5,0.0,0.002,smss.exe,592,None
6,0.0,0.322,lsass.exe,628,None
7,0.0,0.123,winlogon.exe,884,None
8,0.0,0.010,UshUpgradeService.exe,896,None
9,0.0,0.014,csrss.exe,908,None
10,0.0,0.004,wininit.exe,1004,None
11,0.0,0.021,csrss.exe,1016,None
12,0.0,0.038,WavesSvc64.exe,1060,ANSYS\dferguso
13,0.0,0.059,svchost.exe,1076,None
14,0.0,0.391,svchost.exe,1100,None
15,0.0,0.015,WUDFHost.exe,1124,None
16,0.0,0.036,fontdrvhost.exe,1148,None
17,0.0,0.005,fontdrvhost.exe,1156,None
18,0.0,0.206,svchost.exe,1284,None
19,0.0,0.549,Teams.exe,1312,ANSYS\dferguso
20,0.0,0.021,WUDFHost.exe,1336,None
21,0.0,0.013,RtkUGui64.exe,1356,ANSYS\dferguso
22,0.0,0.106,svchost.exe,1360,None
23,0.0,0.116,svchost.exe,1364,None
24,0.0,0.350,dwm.exe,1520,None
25,0.0,0.099,svchost.exe,1568,None
26,0.0,0.229,svchost.exe,1576,None
27,0.0,0.109,SupportAssistAppWire.exe,1588,ANSYS\dferguso
28,0.0,0.090,svchost.exe,1688,None
29,0.0,0.138,svchost.exe,1696,None
...,...,...,...,...,...
359,0.0,1.653,chrome.exe,26508,ANSYS\dferguso
360,0.0,0.097,chrome.exe,26608,ANSYS\dferguso
361,0.0,0.500,GitHubDesktop.exe,26612,ANSYS\dferguso
362,0.0,0.144,chrome.exe,26996,ANSYS\dferguso
363,0.0,0.015,jupyter-notebook.exe,27052,ANSYS\dferguso
364,0.0,0.469,chrome.exe,27408,ANSYS\dferguso
365,0.0,0.167,chrome.exe,27420,ANSYS\dferguso
366,0.0,0.202,LockApp.exe,27500,ANSYS\dferguso
367,0.0,0.127,chrome.exe,27720,ANSYS\dferguso
368,0.0,0.034,splwow64.exe,27840,ANSYS\dferguso
369,0.0,1.273,chrome.exe,28316,ANSYS\dferguso
370,0.0,0.166,MicrosoftPdfReader.exe,28792,ANSYS\dferguso
371,0.0,0.012,Windows.WARP.JITService.exe,29096,None
372,0.0,0.037,svchost.exe,29828,None
373,0.0,0.018,bash.exe,30008,ANSYS\dferguso
374,0.0,0.007,fsnotifier64.exe,30040,ANSYS\dferguso
375,0.0,0.393,Teams.exe,31032,ANSYS\dferguso
376,0.0,0.457,GitHubDesktop.exe,31152,ANSYS\dferguso
377,0.0,0.035,SppExtComObj.Exe,31820,None
378,0.0,0.237,chrome.exe,32304,ANSYS\dferguso
379,0.0,0.338,chrome.exe,32392,ANSYS\dferguso
380,0.0,0.148,chrome.exe,32460,ANSYS\dferguso
381,0.0,0.186,Zoom.exe,32564,ANSYS\dferguso
382,0.0,0.139,OpenWith.exe,32884,ANSYS\dferguso
383,0.0,0.265,SnippingTool.exe,33000,ANSYS\dferguso
384,0.0,0.073,SearchProtocolHost.exe,33476,None
385,0.0,0.137,chrome.exe,33548,ANSYS\dferguso
386,0.0,0.162,chrome.exe,34064,ANSYS\dferguso
387,0.0,0.024,armsvc.exe,34092,None
388,0.0,0.203,WmiPrvSE.exe,34596,None

- There are 389 running programs on my laptop.


- Most of these run as "services," i.e. start when my laptop starts and run "in the background."


- Where is MySQL?

In [19]:
mysql_df = df[df['name'] == 'mysqld.exe']
mysql_df

     cpu_percent  memory_percent        name    pid username
226          0.0           0.017  mysqld.exe  12164     None
234          0.0           0.110  mysqld.exe  12740     None

- Cool. What does this have to do with databases?


- __Ignore the following wizard stuff.__

In [25]:
print("Please ignore this wizard stuff.")
import csv
s_stuff = []
with open("c:\\Users\dferguso\\Documents\\secret_stuff.csv", "r") as in_file:
    rdr = csv.DictReader(in_file)
    for r in rdr:
        s_stuff.append(r)

host = s_stuff[0]['host']
pw = s_stuff[0]['pw']
userid = s_stuff[0]['userid']

url = "mysql+pymysql://" + userid + ":" + pw + "@" + host
print(url)

Please ignore this wizard stuff.
mysql+pymysql://root:dbuserdbuser@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com

- I am now going to show you some stuff you will learn in this course ...

In [32]:
%load_ext sql
url

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'mysql+pymysql://root:dbuserdbuser@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com'

In [35]:
%%sql mysql+pymysql://***:******@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com
use cw_info

0 rows affected.

[]

In [36]:
no_students = %sql select count(*) as count from cw_students
print("\n\nAccording to CourseWorks data loaded into this databases, Don has taught ...", no_students[0][0], "students\n\n")

   mysql+pymysql://dbuser:***@localhost/w4111f19
 * mysql+pymysql://root:***@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com
1 rows affected.


According to CourseWorks data loaded into this databases, Don has taught ... 1451 students

- Which what were the courses?

In [37]:
%sql select id, name, course_no, section, year, semester from cw_courses

   mysql+pymysql://dbuser:***@localhost/w4111f19
 * mysql+pymysql://root:***@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com
15 rows affected.

[('11912', 'COMSE6998_010_2016_3 - TOPICS IN COMPUTER SCIENCE', 'COMSE6998', '010', '2016', '3'),
 ('34758', 'COMSE6998_006_2017_1 - TOPICS IN COMPUTER SCIENCE', 'COMSE6998', '006', '2017', '1'),
 ('47421', 'COMSE6998_014_2017_3 - TOPICS IN COMPUTER SCIENCE', 'COMSE6998', '014', '2017', '3'),
 ('47468', 'COMSW4111_003_2017_3 - INTRODUCTION TO DATABASES', 'COMSW4111', '003', '2017', '3'),
 ('53309', 'COMSW4111_002_2018_1 - INTRODUCTION TO DATABASES', 'COMSW4111', '002', '2018', '1'),
 ('53496', 'ENGIE1006_001_2018_1 - INTRO TO COMP FOR ENG/APP SCI', 'ENGIE1006', '001', '2018', '1'),
 ('59651', 'COMSW3999_063_2018_3 - FIELDWORK', 'COMSW3999', '063', '2018', '3'),
 ('59653', 'COMSW4111_001_2018_3 - INTRODUCTION TO DATABASES', 'COMSW4111', '001', '2018', '3'),
 ('61720', 'ENGIE1102_001_2018_3 - THE ART OF ENGINEERING', 'ENGIE1102', '001', '2018', '3'),
 ('69174', 'COMSE6156_001_2018_3 - TOPICS IN SOFTWARE ENGINEERING: Cloud and Microservice Applications', 'COMSE6156', '001', '2018', '3'),
 ('79571', 'COMSW4111_003_2019_1 - INTRODUCTION TO DATABASES', 'COMSW4111', '003', '2019', '1'),
 ('82004', 'COMSW3999_063_2019_2 - FIELDWORK', 'COMSW3999', '063', '2019', '2'),
 ('85777', 'COMSW4111_002_2019_3 - INTRODUCTION TO DATABASES', 'COMSW4111', '002', '2019', '3'),
 ('87722', 'COMSE6156_001_2019_3 - TOPICS IN SOFTWARE ENGINEERING', 'COMSE6156', '001', '2019', '3'),
 ('91884', 'COMSW4111_H02_2019_3 - INTRODUCTION TO DATABASES', 'COMSW4111', 'H02', '2019', '3')]

- Which course had the most students?

In [39]:
%%sql
SELECT course_id, course_code_full, count(*) as no_students
FROM cw_info.student_course_view
group by course_id, course_code_full
order by no_students desc;

   mysql+pymysql://dbuser:***@localhost/w4111f19
 * mysql+pymysql://root:***@columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com
13 rows affected.

[('79571', 'COMSW4111_003_2019_1 - INTRODUCTION TO DATABASES', 245),
 ('53496', 'ENGIE1006_001_2018_1 - INTRO TO COMP FOR ENG/APP SCI', 204),
 ('59653', 'COMSW4111_001_2018_3 - INTRODUCTION TO DATABASES', 201),
 ('61720', 'ENGIE1102_001_2018_3 - THE ART OF ENGINEERING', 193),
 ('85777', 'COMSW4111_002_2019_3 - INTRODUCTION TO DATABASES', 177),
 ('47468', 'COMSW4111_003_2017_3 - INTRODUCTION TO DATABASES', 138),
 ('53309', 'COMSW4111_002_2018_1 - INTRODUCTION TO DATABASES', 115),
 ('34758', 'COMSE6998_006_2017_1 - TOPICS IN COMPUTER SCIENCE', 78),
 ('69174', 'COMSE6156_001_2018_3 - TOPICS IN SOFTWARE ENGINEERING', 68),
 ('11912', 'COMSE6998_010_2016_3', 59),
 ('47421', 'COMSE6998_014_2017_3 - TOPICS IN COMPUTER SCIENCE', 53),
 ('87722', 'COMSE6156_001_2019_3 - TOPICS IN SOFTWARE ENGINEERING', 48),
 ('82004', 'COMSW3999_063_2019_2 - FIELDWORK', 1)]

__What Did You Just Learn?__

<img src="../../images/wizard.jpg" width="700px">

- But seriously, ...

<hr style="height:1px;">

| <img src="../../images/aws_notebook.jpg" width="900px"> |
| :---: |
| __Process Structure__ |

<hr style="height:1px;">

- The DBMS is a program (or multiple programs) running on a computer (or multiple computers) somewhere.


- To use a database,
    - You write (or run a program).
    - That connects to the DBMS program managing the database.
    - Send commands to the DBMS over a network connection.

__An Aside:__ Where how did I get the CourseWorks data?

In [1]:
import sys
sys.path.append("C:\\Users\\dferguso\\ansys_one_drive\\Columbia\\Projects\\CourseInfo\\BasicTests")

In [2]:
import context as context
context.context['base_url']

'https://courseworks2.columbia.edu/api/v1'

In [7]:
tk = context.context["access_token"]
base_url = context.context['base_url']
headers = {"Authorization": tk}

In [8]:
import requests
url = base_url + "/courses/79571/students"
print("I am going to get data from URL = ", url)

I am going to get data from URL =  https://courseworks2.columbia.edu/api/v1/courses/79571/students

In [5]:
result = requests.get(url=url, headers=headers)
students = result.json()

- I now have information about the students in this class.


- I do not want to put personal information in this notebook for the lecture. So, I am going to hide stuff.

In [15]:
hidden_unis = []
for r in students:
    clear_uni = r['login_id']
    hidden_uni = []
    for c in clear_uni:
        if c.isdigit():
            c="*"
        hidden_uni.append(c)
    hidden_uni = "".join(hidden_uni)
    hidden_unis.append(hidden_uni)

In [16]:
print("There are ", len(hidden_unis), "students in this class.")

There are  246 students in this class.

In [18]:
hidden_unis.sort()
print("The first 10 initials in alphabetical order is: \n", hidden_unis[0:9])

The first 10 initials in alphabetical order is:
 ['aa****', 'al****', 'al****', 'am****', 'amh****', 'ams****', 'an****', 'ank****', 'ap****']

__OK. That was REALLY CONFUSING.__

<hr style="height:1px;">

| <img src="../../images/cloud_and_courseworks.jpg" width="900px"> |
| :---: |
| __Using Cloud APIs and Data__ |

<hr style="height:1px;">

- We tend to think of "the web" as a bunch of sites with UIs we can navigate with a browser.


- The web is increasing evolving to a web of APIs we can call to access interesting information. $\Rightarrow$
It is a big, honking set of linked databases.


- I wrote a program that:
    - Used the CourseWorks API to extract data.
    - Manipulated the data.
    - Created a new database in MySQL in the Amazon cloud.
    - Uploaded the data into the DB for analysis.
    
    
- This is an increasingly common pattern for data usage and analysis.


- In this section, you will get experience consuming web accessible data for analysis and publishing data to the web for analysis.

### Databases versus Files (CSV Files)

- All this relational data looks like spreadsheet data.


- Is a database (and DBMS) simply a spreadsheet file?


- No. And you will find out why in homework 1.

## Introduction to The Relational Model and SQL

### Introduction

<hr style="height:1px;">

| <img src="../../images/relational_definition.jpg" width="900px"> |
| :---: |
| __Relational Model Definition__ |

<hr style="height:1px;">

__Concepts:__ From a pretty good [on-line tutorial](https://www.tutorialspoint.com/dbms/relational_data_model.htm)


- _Tables_ − In relational data model, relations are saved in the format of Tables. This format stores the relation among entities. A table has rows and columns, where rows represents records and columns represent the attributes.


- _Tuple_ − A single row of a table, which contains a single record for that relation is called a tuple.


- _Relation instance_ − A finite set of tuples in the relational database system represents relation instance. Relation instances do not have duplicate tuples.


- _Relation schema_ − A relation schema describes the relation name (table name), attributes, and their names.


- _Relation key_ − Each row has one or more attributes, known as relation key, which can identify the row in the relation (table) uniquely.


- _Attribute domain_ − Every attribute has some pre-defined value scope, known as attribute domain.


__An Aside:__ The best practice is for the attribute domains to be _atomic._

- A column/field type of the form _"last_name, first_name"_ is not atomic.


- There are two distinct domains in the column.


- We will see the advantages and disadvantages of atomic domains during the course.

<hr style="height:1px;">

| <img src="../../images/relation_example.jpg" width="900px"> |
| :---: |
| __Relation Example__ |

<hr style="height:1px;">

<hr style="height:1px;">

| <img src="../../images/relational_query_language.jpg" width="900px"> |
| :---: |
| __Relational Query Language__ |

<hr style="height:1px;">

### Structured Query Language

#### Concept

"SQL; Structured Query Language) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS). It is particularly useful in handling structured data where there are relations between different entities/variables of the data. SQL offers two main advantages over older read/write APIs ... ... First, it introduced the concept of accessing many records with one single command; and second, it eliminates the need to specify how to reach a record, e.g. with or without an index." (https://en.wikipedia.org/wiki/SQL)


- The easiest way to understand is with examples.


- Spreadsheets (Excel, Comma Separated Value Files) are very "relation/table like."

<hr style="height:1px;">

| <img src="../../images/sample_student_csv.jpg" width="900px"> |
| :---: |
| __Sample Comma Separated Value Data__ |

<hr style="height:1px;">

- The corresponding data in a table in MySQL.

<hr style="height:1px;">

| <img src="../../images/sample_student_mysql.jpg" width="900px"> |
| :---: |
| __Sample MySQL Table__ |

<hr style="height:1px;">

- There does not appear to be much difference. __The differences emerge when you examine some use cases.__

### SQL Statements

#### Overview

- There are two classes of SQL statements: _data definition language_ and _data manipulation language._

<hr style="height:1px;">

| <img src="../../images/dbms_end_to_end.jpg" width="900px"> |
| :---: |
| __DBMS SQL Processing__ |

<hr style="height:1px;">

- When I execute the code cells in the notebook with ```%sql``` or ```%%sql``` and hit run,
    - The browser send the text in the cell to the Jupyter notebook server.
    - The notebook server passes the text to an embedded Python interpreter.
    - The Python interpreter is the DBMS client.
    
- When I use _MySQL Workbench,_ the workbench is a program on my laptop that has a user interface.
    - This is the client application.
    - MySQL Workbench and MySQL Community Server are two different products, codebases and running programs.
    
    
- You can also write your own application that forms the SQL commands and sends to the DBMS through the connector.
    - The code cells with Python in them are a version of this model.
    - The code cell is a little application.
    - The browser and Jupyter notebook sever send the code to a Python interpreter to run the application.
    
    
- Demo/Show:
    - MySQL
    - PyCharm
    - Various running processes.

#### Some Helper Code

- You will write programs that use the database through a connector library.


- The programming can be a little tedious. I will provide some helper functions that you can use.


- I had the students implement these functions last semester. I decided that the details of Python string, args, etc. manipulation had little teaching value.


- All of the helper functions are in the GitHub project for the class. You can use for homework and exams.

##### Run a Query

In [22]:
import pymysql

import logging
logger = logging.getLogger()

'''
The default DB connection information. You MUST use this connection information for your assignments
unless we specify otherwise. This means that you will have to:
1. Create the schema lahman2019raw. 
2. Create a user dbuser with the password dbuserdbuser.

We will show how to do this.
'''

def _get_default_connection():
    result = pymysql.connect(host='localhost',
                                 user='dbuser',
                                 password='dbuserdbuser',
                                 db='lahman2019raw',
                                 charset='utf8mb4',
                                 cursorclass=pymysql.cursors.DictCursor)
    return result

def run_q(sql, args=None, fetch=True, cur=None, conn=None, commit=True):
    '''
    Helper function to run an SQL statement.

    :param sql: SQL template with placeholders for parameters.
    :param args: Values to pass with statement.
    :param fetch: Execute a fetch and return data.
    :param conn: The database connection to use. The function will use the default if None.
    :param cur: The cursor to use. This is wizard stuff. Do not worry about it for now.
    :param commit: This is wizard stuff. Do not worry about it.

    :return: A tuple of the form (execute response, fetched data)
    '''

    cursor_created = False
    connection_created = False

    try:

        if conn is None:
            connection_created = True
            conn = _get_default_connection()

        if cur is None:
            cursor_created = True
            cur = conn.cursor()

        if args is not None:
            log_message = cur.mogrify(sql, args)
        else:
            log_message = sql

        logger.debug("Executing SQL = " + log_message)

        res = cur.execute(sql, args)

        if fetch:
            data = cur.fetchall()
        else:
            data = None

        # Do not ask.
        if commit == True:
            conn.commit()

    except Exception as e:
        raise(e)

    return (res, data)

- Simple test.

In [3]:
import json

import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

def t1():

    sql = "select * from lahman2019raw.people where nameLast=%s and birthCity=%s"
    args = ('Williams', 'San Diego')

    result = run_q(sql, args, fetch=True)

    print("Return code = ", result[0])
    print("Data = ")
    if result[1] is not None:
        print(json.dumps(result[1], indent=2))
    else:
        print("None.")

In [4]:
t1()

DEBUG:root:Executing SQL = select * from lahman2019raw.people where nameLast='Williams' and birthCity='San Diego'

Return code =  2
Data =
[
  {
    "playerID": "willite01",
    "birthYear": "1918",
    "birthMonth": "8",
    "birthDay": "30",
    "birthCountry": "USA",
    "birthState": "CA",
    "birthCity": "San Diego",
    "deathYear": "2002",
    "deathMonth": "7",
    "deathDay": "5",
    "deathCountry": "USA",
    "deathState": "FL",
    "deathCity": "Inverness",
    "nameFirst": "Ted",
    "nameLast": "Williams",
    "nameGiven": "Theodore Samuel",
    "weight": "205",
    "height": "75",
    "bats": "L",
    "throws": "R",
    "debut": "1939-04-20",
    "finalGame": "1960-09-28",
    "retroID": "willt103",
    "bbrefID": "willite01"
  },
  {
    "playerID": "willitr01",
    "birthYear": "1992",
    "birthMonth": "4",
    "birthDay": "25",
    "birthCountry": "USA",
    "birthState": "CA",
    "birthCity": "San Diego",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Trevor",
    "nameLast": "Williams",
    "nameGiven": "Trevor Anthony",
    "weight": "230",
    "height": "75",
    "bats": "R",
    "throws": "R",
    "debut": "2016-09-07",
    "finalGame": "2018-09-27",
    "retroID": "willt002",
    "bbrefID": "willitr01"
  }
]

##### Select

- ```SELECT``` reads and returns database from a database.


- We will cover in lectures and use extensively.


- [w3schools](https://www.w3schools.com/sql/sql_select.asp) has a good tutorial that may help in the beginning.


- The ```SELECT``` format is:

```
SELECT column1, column2, ...
FROM table_name
WHERE condition;
```

<u>Example</u>

In [8]:
%%sql

select nameLast, nameFirst, birthCity, birthState, birthYear
    from lahman2019raw.people
    where birthCity='San Diego' and nameLast='Williams'

 * mysql+pymysql://dbuser:***@localhost/w4111f19
2 rows affected.

[('Williams', 'Ted', 'San Diego', 'CA', '1918'),
 ('Williams', 'Trevor', 'San Diego', 'CA', '1992')]

- __Ignore the ```%sql``` and ```%%sql``` stuff for now. You SQL statements in programs will not use it.__


<u>Some Helper Code</u>

In [9]:
def template_to_where_clause(template):
    """

    :param template: One of those weird templates
    :return: WHERE clause corresponding to the template.
    """

    if template is None or template == {}:
        result = (None, None)
    else:
        args = []
        terms = []

        for k,v in template.items():
            terms.append(" " + k + "=%s ")
            args.append(v)

        w_clause = "AND".join(terms)
        w_clause = " WHERE " + w_clause

        result = (w_clause, args)

    return result

def create_select(table_name, template, fields, order_by=None, limit=None, offset=None):
    """
    Produce a select statement: sql string and args.

    :param table_name: Table name: May be fully qualified dbname.tablename or just tablename.
    :param fields: Columns to select (an array of column name)
    :param template: One of Don Ferguson's weird JSON/python dictionary templates.
    :param order_by: Ignore for now.
    :param limit: Ignore for now.
    :param offset: Ignore for now.
    :return: A tuple of the form (sql string, args), where the sql string is a template.
    """

    if fields is None:
        field_list = " * "
    else:
        field_list = " " + ",".join(fields) + " "

    w_clause, args = template_to_where_clause(template)

    sql = "select " + field_list + " from " +  table_name + " " + w_clause

    return (sql, args)

In [14]:
def t2():

    table_name = "lahman2019raw.people"
    fields = ['nameLast', 'nameFirst', 'birthYear', 'birthState', 'birthMonth']
    template = { "nameLast": "Williams", "birthCity": "San Diego"}
    sql, args = create_select(table_name, template, fields)
    print("SQL = ", sql, ", args = ", args)

    result = run_q(sql, args)
    if result[1] is not None:
        print(json.dumps(result[1], indent=2))
    else:
        print("None.")

In [15]:
t2()

DEBUG:root:Executing SQL = select  nameLast,nameFirst,birthYear,birthState,birthMonth  from lahman2019raw.people  WHERE  nameLast='Williams' AND birthCity='San Diego'

SQL =  select  nameLast,nameFirst,birthYear,birthState,birthMonth  from lahman2019raw.people  WHERE  nameLast=%s AND birthCity=%s  , args =  ['Williams', 'San Diego']
[
  {
    "nameLast": "Williams",
    "nameFirst": "Ted",
    "birthYear": "1918",
    "birthState": "CA",
    "birthMonth": "8"
  },
  {
    "nameLast": "Williams",
    "nameFirst": "Trevor",
    "birthYear": "1992",
    "birthState": "CA",
    "birthMonth": "4"
  }
]

##### Insert

- The simple version of ```INSERT``` is:

```
INSERT INTO table_name ( field1, field2,...fieldN )
   VALUES
   ( value1, value2,...valueN );
```

- If you do not include ```( field1, field2,...fieldN )``` in the statement, the default is all of the table's columns in the order defined in the table definition.


- __Note:__
    - I do not want to update the Lahman database because we will be analyzing it. So, I will use a different sample database: [MySQL Sample Database](http://www.mysqltutorial.org/mysql-sample-database.aspx)
    - We will periodically use this schema, and I will discuss in the future.
    - I jump around using different databases for various reasons, but this also highlights the flexibility of the relational model and SQL. A simple, core language and models supports a very broad set of data.


<u>Example</u>

- The current set of office locations for the company.

In [16]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
8 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA')]

- Add a new row.

In [19]:
%%sql
    insert into classicmodels.offices
        (officeCode, city, phone, addressLine1, state, country, postalCode, territory)
    values
        (9, "Boston", "+1 617-555-1212", "One Government Center", "MA", "USA", "02102", "NA")

 * mysql+pymysql://dbuser:***@localhost/w4111f19
1 rows affected.

[]

In [20]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
9 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA'),
 ('9', 'Boston', '+1 617-555-1212', 'One Government Center', None, 'MA', 'USA', '02102', 'NA')]

<u>Helper Code</u>

In [23]:
def create_insert(table_name, row):
    """

    :param table_name: A table name, which may be fully qualified.
    :param row: A Python dictionary of the form: { ..., "column_name" : value, ...}
    :return: SQL template string, args for insertion into the template
    """

    result = "Insert into " + table_name + " "
    cols = []
    vals = []

    # This is paranoia. I know that calling keys() and values() should return in matching order,
    # but in the long term only the paranoid survive.
    for k,v in row.items():
        cols.append(k)
        vals.append(v)

    col_clause = "(" + ",".join(cols) + ") "

    no_cols = len(cols)
    terms = ["%s"]*no_cols
    terms = ",".join(terms)
    value_clause = " values (" + terms + ")"

    result += col_clause + value_clause

    return (result, vals)

In [31]:
def t3():

    table_name = "classicmodels.offices"
    row = {
        "officeCode": "13",
        "city": "Minas Tirith",
        "state": "Minas Tirith",
        "addressLine1": "23 Level 3",
        "phone": "Palatir",
        "country": "Gondor",
        "postalCode": "12345",
        "territory": "ME"
    }

    sql, args = create_insert(table_name, row)
    print("SQL = ", sql, ", args = ", args)

    result = run_q(sql, args, fetch=False, commit=True)
    if result[1] is not None:
        print(json.dumps(result[1], indent=2))
    else:
        print("None.")

In [33]:
t3()

DEBUG:root:Executing SQL = Insert into classicmodels.offices (officeCode,city,state,addressLine1,phone,country,postalCode,territory)  values ('13','Minas Tirith','Minas Tirith','23 Level 3','Palatir','Gondor','12345','ME')

SQL =  Insert into classicmodels.offices (officeCode,city,state,addressLine1,phone,country,postalCode,territory)  values (%s,%s,%s,%s,%s,%s,%s,%s) , args =  ['13', 'Minas Tirith', 'Minas Tirith', '23 Level 3', 'Palatir', 'Gondor', '12345', 'ME']
None.

In [34]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
10 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('13', 'Minas Tirith', 'Palatir', '23 Level 3', None, 'Minas Tirith', 'Gondor', '12345', 'ME'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA'),
 ('9', 'Boston', '+1 617-555-1212', 'One Government Center', None, 'MA', 'USA', '02102', 'NA')]

#### Update

- The ```UPDATE``` statement changes rows that match a condition.


- The simple version is:

```
UPDATE [LOW_PRIORITY] [IGNORE] table_name 
SET 
    column_name1 = expr1,
    column_name2 = expr2,
    ...
[WHERE
    condition];
```

<u>Example</u>

In [35]:
%%sql
update classicmodels.offices
    set phone="Broken Palantir", addressLine2="Apt. 2"
    where
        city="Minas Tirith"

 * mysql+pymysql://dbuser:***@localhost/w4111f19
1 rows affected.

[]

In [36]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
10 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('13', 'Minas Tirith', 'Broken Palantir', '23 Level 3', 'Apt. 2', 'Minas Tirith', 'Gondor', '12345', 'ME'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA'),
 ('9', 'Boston', '+1 617-555-1212', 'One Government Center', None, 'MA', 'USA', '02102', 'NA')]

<u>Helper Code</u>

In [37]:

def create_update(table_name, new_values, template):
    """

    :param new_values: A dictionary containing cols and the new values.
    :param template: A template to form the where clause.
    :return: An update statement template and args.
    """
    set_terms = []
    args = []

    for k,v in new_values.items():
        set_terms.append(k + "=%s")
        args.append(v)

    s_clause = ",".join(set_terms)
    w_clause, w_args = template_to_where_clause(template)

    # There are %s in the SET clause and the WHERE clause. We need to form
    # the combined args list.
    args.extend(w_args)

    sql = "update " + table_name + " set " + s_clause + " "+ w_clause

    return sql, args

In [39]:
def t4():

    table_name = "classicmodels.offices"
    new_cols = {
        "city": "Minas Morgul",
        "state": "Morgul Vale",
        "addressLine1": "1 Shelob Cave",
        "phone": "Ick",
        "country": "Mordor",
        "postalCode": "66666"
    }

    template = { "city": "Minas Tirith", "state": "Minas Tirith"}

    sql, args = create_update(table_name, new_cols, template)
    print("SQL = ", sql, ", args = ", args)

    result = run_q(sql, args, fetch=False, commit=True)
    if result[1] is not None:
        print(json.dumps(result[1], indent=2))
    else:
        print("None.")

In [40]:
t4()

DEBUG:root:Executing SQL = update classicmodels.offices set city='Minas Morgul',state='Morgul Vale',addressLine1='1 Shelob Cave',phone='Ick',country='Mordor',postalCode='66666'  WHERE  city='Minas Tirith' AND state='Minas Tirith'

SQL =  update classicmodels.offices set city=%s,state=%s,addressLine1=%s,phone=%s,country=%s,postalCode=%s  WHERE  city=%s AND state=%s  , args =  ['Minas Morgul', 'Morgul Vale', '1 Shelob Cave', 'Ick', 'Mordor', '66666', 'Minas Tirith', 'Minas Tirith']
None.

In [41]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
10 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('13', 'Minas Morgul', 'Ick', '1 Shelob Cave', 'Apt. 2', 'Morgul Vale', 'Mordor', '66666', 'ME'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA'),
 ('9', 'Boston', '+1 617-555-1212', 'One Government Center', None, 'MA', 'USA', '02102', 'NA')]

#### Delete

- The ```DELETE``` statement deletes all rows matching a ```WHERE``` condition.


- The syntax is:

```
DELETE FROM table_name [WHERE Clause]
```

- ```DELETE``` is basically the same as a ```SELECT``` without the column list or an ```UPDATE``` without the ```SET``` clause.

<u>Example</u>

In [42]:
%sql delete from classicmodels.offices where city="Minas Morgul"

 * mysql+pymysql://dbuser:***@localhost/w4111f19
1 rows affected.

[]

In [44]:
%sql select * from classicmodels.offices

 * mysql+pymysql://dbuser:***@localhost/w4111f19
9 rows affected.

[('1', 'San Francisco', '+1 650 219 4782', '100 Market Street', 'Suite 300', 'CA', 'USA', '94080', 'NA'),
 ('2', 'Boston', '+1 215 837 0825', '1550 Court Place', 'Suite 102', 'MA', 'USA', '02107', 'NA'),
 ('3', 'NYC', '+1 212 555 3000', '523 East 53rd Street', 'apt. 5A', 'NY', 'USA', '10022', 'NA'),
 ('4', 'Paris', '+33 14 723 4404', "43 Rue Jouffroy D'abbans", None, None, 'France', '75017', 'EMEA'),
 ('5', 'Tokyo', '+81 33 224 5000', '4-1 Kioicho', None, 'Chiyoda-Ku', 'Japan', '102-8578', 'Japan'),
 ('6', 'Sydney', '+61 2 9264 2451', '5-11 Wentworth Avenue', 'Floor #2', None, 'Australia', 'NSW 2010', 'APAC'),
 ('7', 'London', '+44 20 7877 2041', '25 Old Broad Street', 'Level 7', None, 'UK', 'EC2N 1HN', 'EMEA'),
 ('8', 'New York', '+1 212 555-1212', 'W 116th Street', 'and Broadway', 'NY', 'USA', '10027', 'NA'),
 ('9', 'Boston', '+1 617-555-1212', 'One Government Center', None, 'MA', 'USA', '02102', 'NA')]

<u>Help Code</u>

- Umm, just modify/simplify the code for ```SELECT.```

#### CREATE TABLE

- What was the code for creating the tables and loading the data in the first place?


- There are several approaches to creating a table.
    - Use the MySQL Workbench or similar tool. There are online tutorials. __I will give a demo now.__
    - Write and execute a ```CREATE TABLE``` statement. We will cover in the course.
    
    
- How did the data get in the table? There are several choices:
    - MySQL Workbench and others tools have data import wizards.
    - There is a ```LOAD TABLE FROM ...```
    - You can write code with ```INSERT``` statements.
    
    
- __I will demo creating and importing some of the Lahman 2019 data now.__

### Comments

- When we discuss homework 1, you will see that you use these functions in the implementation.


- The code above is simple, but:
    - Asking you to figure it out by yourselves has little teaching value in a DB class.
    - Some of you would get bogged down or overwhelmed having to figure out the string, dictionary, etc in addition to the HW and DB concepts.
    
    
- There may be some minor errors in the code. I cut out of my solution to the HW and simplified. I had to remove some code implementing concepts we will cover later in the semester, e.g. transactions.


- You can find the Python files in: https://github.com/donald-f-ferguson/w4111-Databases/tree/master/Examples.


- If we find mistakes, I will update in the GitHub repository.


- If you complain about any errors, remember that I did not give prior years ANY code.


- __Finally,__ the complete versions of the ```SELECT, INSERT, UPDATE,``` and ```DELETE``` statement are much more complex and have significant additional capabilities, some of which we will cover.

### Motivating Use Cases

#### Overview

- When people first start using databases,
    - The concept seems complex, because it is and because the concept is new.
    - The examples are simple.
    - Students wonder why someone would use the DB instead of just writing simple code.


- We will see some very hard things to do with "code" and the value of databases this semester.


- I want go give a few motivating example now, however.

#### Full Data Model

- Lahman 2019 is large and relatively complex. I will use the [Classic Models](http://www.mysqltutorial.org/mysql-sample-database.aspx) to provide some simple motivation.


- The data model is below. We will cover the meanings of the symbols later.

<hr style="height:2pm;">


| <img src="../../images/classicmodels_schema.png"> |
| :---: |
| __Classic Models Data Model__ |


<hr style="height:2pm;">

- The schema consists of the following tables:
    - Customers: stores customer’s data.
    - Products: stores a list of scale model cars.
    - ProductLines: stores a list of product line categories.
    - Orders: stores sales orders placed by customers.
    - OrderDetails: stores sales order line items for each sales order.
    - Payments: stores payments made by customers based on their accounts.
    - Employees: stores all employee information as well as the organization structure such as who reports to whom.
    - Offices: stores sales office data.

#### Motivating Example

- Write a function that produces ```customerNumber, orderNumber, total_value, status, country``` where ```total_value``` is the sum of the ```quantityOrdered``` and ``priceEach``` for all entries in an order.


- Support filtering the answer by ```customerNumber, orderNumber, status``` and/or ```country.```

In [45]:
def revenue_report(customer_number=None, order_number=None, order_status=None, country=None):
    """
    Returns the orders and total value (sum of value of order items).

    :param customer_number: Customer to get orders for. None gets all.
    :param order_number: Same for order number.
    :param order_status: Same for order status.
    :param country: Same for customer country
    :return: Matching information.
    """

    sql = """
        select
	        customers.customerNumber, customerName, customers.country,
            orders.orderNumber, orders.status, 
            (select sum(orderdetails.quantityOrdered*orderdetails.priceEach)
		        from classicmodels.orderdetails where orders.orderNumber = orderDetails.orderNumber) as order_value
        from classicmodels.customers join classicmodels.orders
        where 
	    customers.customerNumber = orders.customerNumber
    """

    args = []
    if customer_number is not None:
        sql += " and customers.customerNumber = %s"
        args.append(customer_number)
    if order_number is not None:
        sql += " and orderNumber = %s"
        args.append(order_number)
    if order_status is not None:
        sql += " and status = %s"
        args.append(order_status)
    if country is not None:
        sql += " and country = %s"
        args.append(country)

    result = run_q(sql, args, fetch=True, commit=True)
    return result

In [46]:
def t5():

    
    print("Result: number of rows = ", result[0])
    print("Data = \n", json.dumps(result[1], indent=2, default=str))

In [52]:
import pandas as pd

logger.setLevel(logging.WARN)

result = revenue_report(order_status="In Process", country="Belgium")

rep = pd.DataFrame(result[1])
rep

   country customerName  customerNumber  orderNumber order_value      status
0  Belgium   Petit Auto             314        10423     8597.73  In Process

In [54]:
result2 = revenue_report(country="France")

logger.setLevel(logging.DEBUG)

rep2 = pd.DataFrame(result2[1])
rep2

DEBUG:root:Executing SQL =
        select
	        customers.customerNumber, customerName, customers.country,
            orders.orderNumber, orders.status,
            (select sum(orderdetails.quantityOrdered*orderdetails.priceEach)
		        from classicmodels.orderdetails where orders.orderNumber = orderDetails.orderNumber) as order_value
        from classicmodels.customers join classicmodels.orders
        where
	    customers.customerNumber = orders.customerNumber
     and country = 'France'

,country,customerName,customerNumber,orderNumber,order_value,status
0,France,Atelier graphique,103,10123,14571.44,Shipped
1,France,Atelier graphique,103,10298,6066.78,Shipped
2,France,Atelier graphique,103,10345,1676.14,Shipped
3,France,La Rochelle Gifts,119,10275,47924.19,Shipped
4,France,La Rochelle Gifts,119,10315,19501.82,Shipped
5,France,La Rochelle Gifts,119,10375,49523.67,Shipped
6,France,La Rochelle Gifts,119,10425,41623.44,In Process
7,France,"Saveley & Henriot, Co.",146,10194,39712.10,Shipped
8,France,"Saveley & Henriot, Co.",146,10208,49614.72,Shipped
9,France,"Saveley & Henriot, Co.",146,10227,40978.53,Shipped
10,France,Daedalus Designs Imports,171,10180,42783.81,Shipped
11,France,Daedalus Designs Imports,171,10224,18997.89,Shipped
12,France,"La Corne D'abondance, Co.",172,10114,33383.14,Shipped
13,France,"La Corne D'abondance, Co.",172,10286,1960.80,Shipped
14,France,"La Corne D'abondance, Co.",172,10336,51209.58,Shipped
15,France,Mini Caravy,209,10241,36069.26,Shipped
16,France,Mini Caravy,209,10255,4632.31,Shipped
17,France,Mini Caravy,209,10405,35157.75,Shipped
18,France,Alpha Cognac,242,10136,14232.70,Shipped
19,France,Alpha Cognac,242,10178,33818.34,Shipped
20,France,Alpha Cognac,242,10397,12432.32,Shipped
21,France,Lyon Souveniers,250,10134,23419.47,Shipped
22,France,Lyon Souveniers,250,10356,26311.63,Shipped
23,France,Lyon Souveniers,250,10395,17928.09,Shipped
24,France,Auto Associés & Cie.,256,10216,5759.42,Shipped
25,France,Auto Associés & Cie.,256,10304,53116.99,Shipped
26,France,Marseille Mini Autos,350,10122,50824.66,Shipped
27,France,Marseille Mini Autos,350,10344,18888.31,Shipped
28,France,Marseille Mini Autos,350,10364,1834.56,Shipped
29,France,Reims Collectables,353,10121,16700.47,Shipped
30,France,Reims Collectables,353,10137,13920.26,Shipped
31,France,Reims Collectables,353,10343,17104.91,Shipped
32,France,Reims Collectables,353,10359,32600.61,Shipped
33,France,Reims Collectables,353,10398,46656.94,Shipped
34,France,Auto Canal+ Petit,406,10211,49165.16,Shipped
35,France,Auto Canal+ Petit,406,10252,25080.96,Shipped
36,France,Auto Canal+ Petit,406,10402,12190.85,Shipped

- The function and SQL statement may seem complex.

```
select
    customers.customerNumber, customerName, customers.country,
    orders.orderNumber, orders.status, 
    (select sum(orderdetails.quantityOrdered*orderdetails.priceEach)
        from classicmodels.orderdetails where orders.orderNumber = orderDetails.orderNumber) as order_value
from classicmodels.customers join classicmodels.orders
where 
    customers.customerNumber = orders.customerNumber
    and country = 'France'
```

- But, you need to compare to the alternative. The query execution steps that the DB performs for this query are:

<hr style="height:2px;">

| <img src="../../images/query_example_plan.jpg" > |
| :---: |
| __Sample Query Execution__ |


- Each of the symbols corresponds to a Python function you would have to write. I did not write the actual code because I am lazy and know the value of SQL.


- If any of you think SQL is not simpler, please raise your hand. What could happen?

## Data modeling

### Overview

- There are several types of models that teams sometimes use in projects. Some common ones are:
    1. Structural/component model.
    2. (Business) process model.
    3. Data model.


<hr style="height:1px;">

| <img src="../../images/component_model.jpg" width="900px"> |
| :---: |
| __Structure/Component Model__ |

<hr style="height:1px;">

| <img src="../../images/bpmn_diagram.jpg" width="900px"> |
| :---: |
| __BPMN Diagram__ |

<hr style="height:1px;">

| <img src="../../images/data_model_diagram.jpg" width="900px"> |
| :---: |
| __Data Model Diagram__ |

- Teams use modeling for several reasons:
    - Documentation precision: If you use PowerPoint, it is sometimes not clear what symbols mean and diagrams can use different symbols if done by different people.
    - Code generation: There are tools that will process model files and generate things:
        - Database schema definition and creation.
        - Application code.
        - SW installation and configuration scripts.

- Complex projects may use several types of modeling:

<hr style="height:1px;">

| <img src="../../images/datamodel1.jpeg"> |
| :---: |
| [Data Model](https://en.wikipedia.org/wiki/Data_model) |

### Data Modeling 

- “Data modeling (data modelling) is the analysis of data objects and their relationships to other data objects. Data modeling is often the first step in database design and object-oriented programming as the designers first create a conceptual model of how data items relate to each other. Data modeling involves a progression from conceptual model to logical model to physical schema.” (http://www.webopedia.com/TERM/D/data_modeling.html)


- Conceptual-Logical-Physical

| <img src="../../images/conceptuallogicalphysical.jpeg"> |
| :---: |
| [Data Model](https://en.wikipedia.org/wiki/Data_model) |


- “What is a datamodel?
A data model is a __notation__ for describing data or information. The description generally consists of three parts:
    - Structure of data.
    - Operations on the data.
    - Constraints on the data.”<br>
(Database Systems: The Complete Book (2nd Edition)
by Hector Garcia-Molina (Author), Jeffrey D. Ullman (Author), Jennifer Widom (Author))


- __Notation:__ 
    - "A visual notation is a graphical representation. It consists of graphical symbols, their definitions, and a visual grammar. Some examples of graphical symbols are: lines, surfaces, volumes, textual labels and spatial relationships. These elements are used to build the visual vocabulary of a notation; Mind Maps for example, consist of lines and labels. Visual representations are effective because they convey information more concisely and precisely than language. They are also better remembered." (https://www.sciencedaily.com/releases/2013/07/130718161429.htm)
    - Think "well-defined clipart" with grammar (rules, meaning)

| <img src="../../images/notation1.jpeg"> |
| :---: |
| __Visual Notation__ |

<br>
<hr>
<br>

| <img src="../../images/notation2.jpeg"> |
| :---: |
| __Visual Notation__ |

- We will use [Crow's Foot Notation](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#Crow's_foot_notation)
    - Simple, clear, etc.
    - There are more powerful and complex notations, but getting carried away is easy.
    - The textbook uses [Chen's Notation.](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#Entity%E2%80%93relationship_modeling)

### Modling Cccurs in Many  Application Domains

Some randomly (by Google) selected examples.
<br><br>


| <img src="../../images/lifescience.gif"> |
| :---: |
| ["Database application model and its service for drug discovery in Model-driven architecture"](https://doi.org/10.1186/s40537-015-0024-1) |

<br><br>

| <img src="../../images/enviro2.jpg" width="100%"> |
| :---: |
| [Environmental Data](http://geotech.com/envirodata) |

<br><br>

| <img src="../../images/ukgov.png" widht="75%"> |
| :---: |
| [Government](https://gds.blog.gov.uk/2013/10/31/government-as-a-data-model-what-i-learned-in-estonia/) as a Data Model |

# Homework 1

__The moment you have all been dreading!__

## Setup

### Download and Installation

- Download, install and configure.
    - [MySQL Community Server](https://dev.mysql.com/downloads/mysql/)
    - [MySQL Workbench](https://dev.mysql.com/downloads/workbench/)
    - Optional but strongly recommended:
        - [PyCharm Professional](https://www.jetbrains.com/pycharm/)
        - Follow the instructions for getting a free [student license.](https://www.jetbrains.com/student/)


- When you install MySQL, you will have to set a user ID and password. MySQL may generate a password.
    - Choose the legacy, version 5 or standard password security.
    - Save the password somewhere you can locate it. 
    - Do not use your laptop password.
    - When you come to my office and I need to fix something, __I will need that password.__
    
    
- Download the _comma separated value_ format of the [Lahman Baseball Statistics Data.](http://www.seanlahman.com/baseball-archive/statistics/)

### Setup Project and Database

- __Demo, Explain and Record for class.__

### The Data and Data Model

- Full datamodel

| <img src="../../images/lahman2016.png" width="66%"><br><br> |
| :---: |
| __Full Lahman Data Model__ |


- Interesting subset (for now and 1st project).
    
| <img src="../../images/lahman2017-1.jpeg" width="100%"><br><br>   |
| :--: |
| __Initial Subset__ |

- Data model
    1. You can think of each one of the rectangles being a single row (_entity_) in a comma separated value file.
    1. Entries in entity are column names and data types.
    1. Lines indicate how to use columns from one file to find columns in another file. For example
        1. playerID can be used to find name information in Master.
        2. playerID can be use to find batting information in Batting.
        

- There are additional semantics that we will enforce (or the DBMS) will enforce.
    - Primary Key: A set of columns for which a given combination of values occurs at most once.
    - Index: Helper data structure that speeds up operations.
    - Integrity constraints: A record can exist in entity A only if there is a corresponding entry in entity B.
    
    
| <img src="../../images/coms4111-slides-92.jpg" width="100%"><br><br>   |
| :--: |
| __Additional Semantics__ |

- My examples will compare a relational database to writing code in Python that manipulates CSV files.


- A more complete, detailed solution will be HW 1. 


- "In computing, a comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. A CSV file stores tabular data (numbers and text) in plain text. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. The use of the comma as a field separator is the source of the name for this file format." (https://en.wikipedia.org/wiki/Comma-separated_values)

| <img src="../../images/people_xls.jpeg"> |
| :---: |
| __People.csv in Excel__ |

<u>What is in the file?</u>
```
playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,deathCountry,deathState,deathCity,nameFirst,nameLast,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID
aardsda01,1981,12,27,USA,CO,Denver,,,,,,,David,Aardsma,David Allan,215,75,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
aaronha01,1934,2,5,USA,AL,Mobile,,,,,,,Hank,Aaron,Henry Louis,180,72,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
aaronto01,1939,8,5,USA,AL,Mobile,1984,8,16,USA,GA,Atlanta,Tommie,Aaron,Tommie Lee,190,75,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
aasedo01,1954,9,8,USA,CA,Orange,,,,,,,Don,Aase,Donald William,190,75,R,R,1977-07-26,1990-10-03,aased001,aasedo01
abadan01,1972,8,25,USA,FL,Palm Beach,,,,,,,Andy,Abad,Fausto Andres,184,73,L,L,2001-09-10,2006-04-13,abada001,abadan01
abadfe01,1985,12,17,D.R.,La Romana,La Romana,,,,,,,Fernando,Abad,Fernando Antonio,220,73,L,L,2010-07-28,2017-10-01,abadf001,abadfe01
abadijo01,1850,11,4,USA,PA,Philadelphia,1905,5,17,USA,NJ,Pemberton,John,Abadie,John W.,192,72,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
abbated01,1877,4,15,USA,PA,Latrobe,1957,1,6,USA,FL,Fort Lauderdale,Ed,Abbaticchio,Edward James,170,71,R,R,1897-09-04,1910-09-15,abbae101,abbated01
abbeybe01,1869,11,11,USA,VT,Essex,1962,6,11,USA,VT,Colchester,Bert,Abbey,Bert Wood,175,71,R,R,1892-06-14,1896-09-23,abbeb101,abbeybe01
abbeych01,1866,10,14,USA,NE,Falls City,1926,4,27,USA,CA,San Francisco,Charlie,Abbey,Charles S.,169,68,L,L,1893-08-16,1897-08-19,abbec101,abbeych01
abbotda01,1862,3,16,USA,OH,Portage,1930,2,13,USA,MI,Ottawa Lake,Dan,Abbott,Leander Franklin,190,71,R,R,1890-04-19,1890-05-23,abbod101,abbotda01
abbotfr01,1874,10,22,USA,OH,Versailles,1935,6,11,USA,CA,Los Angeles,Fred,Abbott,Harry Frederick,180,70,R,R,1903-04-25,1905-09-20,abbof101,abbotfr01
abbotgl01,1951,2,16,USA,AR,Little Rock,,,,,,,Glenn,Abbott,William Glenn,200,78,R,R,1973-07-29,1984-08-08,abbog001,abbotgl01
abbotje01,1972,8,17,USA,GA,Atlanta,,,,,,,Jeff,Abbott,Jeffrey William,190,74,R,L,1997-06-10,2001-09-29,abboj002,abbotje01
abbotji01,1967,9,19,USA,MI,Flint,,,,,,,Jim,Abbott,James Anthony,200,75,L,L,1989-04-08,1999-07-21,abboj001,abbotji01
abbotku01,1969,6,2,USA,OH,Zanesville,,,,,,,Kurt,Abbott,Kurt Thomas,180,71,R,R,1993-09-07,2001-04-13,abbok002,abbotku01
abbotky01,1968,2,18,USA,MA,Newburyport,,,,,,,Kyle,Abbott,Lawrence Kyle,200,76,L,L,1991-09-10,1996-08-24,abbok001,abbotky01
abbotod01,1886,9,5,USA,PA,New Eagle,1933,4,13,USA,DC,Washington,Ody,Abbott,Ody Cleon,165,69,L,R,1910-09-10,1910-10-15,abboo101,abbotod01
abbotpa01,1967,9,15,USA,CA,Van Nuys,,,,,,,Paul,Abbott,Paul David,185,75,R,R,1990-08-21,2004-08-07,abbop001,abbotpa01
aberal01,1927,7,31,USA,OH,Cleveland,1993,5,20,USA,OH,Garfield Heights,Al,Aber,Albert Julius,195,74,L,L,1950-09-15,1957-09-11,abera101,aberal01
abercda01,1850,1,2,USA,OK,Fort Towson,1939,11,11,USA,PA,Philadelphia,Frank,Abercrombie,Francis Patterson,,,,,1871-10-21,1871-10-21,aberd101,abercda01
abercre01,1980,7,15,USA,GA,Columbus,,,,,,,Reggie,Abercrombie,Reginald Damascus,215,75,R,R,2006-04-04,2008-09-28,aberr001,abercre01
abernbi01,1929,1,30,USA,CA,Torrance,2006,2,19,USA,CA,Yucaipa,Bill,Abernathie,William Edward,190,70,R,R,1952-09-27,1952-09-27,aberb101,abernbi01
abernbr01,1977,9,23,USA,GA,Atlanta,,,,,,,Brent,Abernathy,Michael Brent,185,73,R,R,2001-06-25,2005-09-29,aberb001,abernbr01
abernte01,1921,10,30,USA,NC,Bynum,2001,11,16,USA,NC,Charlotte,Ted,Abernathy,Talmadge Lafayette,210,74,R,L,1942-09-19,1944-04-29,abert102,abernte01
abernte02,1933,3,6,USA,NC,Stanley,2004,12,16,USA,NC,Gastonia,Ted,Abernathy,Theodore Wade,215,76,R,R,1955-04-13,1972-09-30,abert101,abernte02
abernwo01,1915,2,1,USA,NC,Forest City,1994,12,5,USA,KY,Louisville,Woody,Abernathy,Virgil Woodrow,170,72,L,L,1946-07-28,1947-04-17,aberw101,abernwo01
aberscl01,1921,8,28,USA,IL,Chicago,1973,6,23,USA,CA,Vallejo,Cliff,Aberson,Clifford Alexander,200,72,R,R,1947-07-18,1949-05-09,aberc101,aberscl01
ablesha01,1883,10,4,USA,TX,Terrell,1951,2,8,USA,TX,San Antonio,Harry,Ables,Harry Terrell,200,74,R,L,1905-09-04,1911-05-05,ableh101,ablesha01
```

## Homework 1 Definition

### Introduction

#### Concept

- Different database management systems have different APIs and connection libraries.


- The schema (columns, types, etc) of a database evolves and changes as applications evolve and change.


- The choice of a database management system for an application may change over time as requirements change.


- A well designed application _encapsulates_ the access to a persistent data type into a single module/object: a data access object]:(https://www.tutorialspoint.com/design_pattern/data_access_object_pattern)
    - All application logic in all modules, functions, classes uses methods on the data access object.
    - Code changes due to changes in the choice of DBMS, different APIs to DBMS, schema changes, etc. occur in the DAO, preventing the need to change dozens of functions, classes, etc.
    

- This is an example of a [software design pattern:](https://en.wikipedia.org/wiki/Software_design_pattern) "In software engineering, a software design pattern is a general, reusable solution to a commonly occurring problem (... ...) in software design. (... ...) It is a description or template for how to solve a problem that can be used in many different situations. Design patterns are formalized best practices that the programmer can use to solve common problems when designing an application or system."


- There are many different versions and names for the data access object design pattern.  
    
    
- HW1 implements a very simple implementation of the concept. We will demonstrate writing a single set of application functions that can access data in a CSV file or an RDB table.


- The level of programming skill necessary to solve the HW is what you learned in 1004, 1006 or 1007.


- Some of the course TAs who are not CS majors can tell you value of learning some of the concepts in the classes homeworks.

#### Learning Objectives

1. Get very simple experience with the concept of design patterns. The concept is useful, recurring and cool to talk about on internship interviews.
<br><br>
2. Understand the value of using a DBMS and how they simplify working with data compared to just programming to files.
<br><br>
3. Begin to understand the architecture and implementation of DBMS, which we cover in module II.
<br><br>
4. Develop basic skills for importing raw data into DBMS for analysis.

### Implementation Template

- You can clone an implementation template from GitHub: https://github.com/donald-f-ferguson/W4111_F19_HW1

<hr style="height:1px;">

| <img src="../../images/hw1_template.jpg" width="900px"> |
| :---: |
| __Implementation Template__ |

<hr style="height:1px;">

- If you have no idea what I am talking about, I am going to hold and record a recitation in which I go through:
    - Starting PyCharm.
    - Creating and cloning the project.
    - Configuring the project settings.
    

- The core implemenation files are below.

In [ ]:
# Import package to enable defining abstract classes in Python.
# Do not worry about understanding abstract base classes. This is just a class that defines
# some methods that subclasses must implement.
from abc import ABC, abstractmethod

import logging

class BaseDataTable(ABC):
    """
    The implementation classes (XXXDataTable) for CSV database, relational, etc. will extend the
    base class and implement the abstract methods.
    """

    def __init__(self, table_name, connect_info, key_columns=None, debug=True):
        """

        :param table_name: Name of the table. Subclasses interpret the exact meaning of table_name.
        :param connect_info: Dictionary of parameters necessary to connect to the data. See examples in subclasses.
        :param key_columns: List, in order, of the columns (fields) that comprise the primary key.
            A primary key is a set of columns whose values are unique and uniquely identify a row. For Appearances,
            the columns are ['playerID', 'teamID', 'yearID']
        :param debug: If true, print debug messages.
        """
        self._table_name = table_name
        self._connect_info = connect_info
        self._key_columns = key_columns
        self._debug = debug

    @abstractmethod
    def find_by_primary_key(self, key_fields, field_list=None):
        """

        :param key_fields: The values for the key_columns, in order, to use to find a record. For example,
            for Appearances this could be ['willite01', 'BOS', '1960']
        :param field_list: A subset of the fields of the record to return. The table may have many
            additional columns, but the caller only requests this subset.
        :return: None, or a dictionary containing the requested columns/values for the row.
        """
        pass

    @abstractmethod
    def find_by_template(self, template, field_list=None, limit=None, offset=None, order_by=None):
        """

        :param template: A dictionary of the form { "field1" : value1, "field2": value2, ...}. The function will return
            a derived table containing the rows that match the template.
        :param field_list: A list of requested fields of the form, ['fielda', 'fieldb', ...]
        :param limit: Do not worry about this for now.
        :param offset: Do not worry about this for now.
        :param order_by: Do not worry about this for now.
        :return: A derived table containing the computed rows.
        """
        pass

    @abstractmethod
    def insert(self, new_record):
        """

        :param new_record: A dictionary representing a row to add to the set of records. Raises an exception if this
            creates a duplicate primary key.
        :return: None
        """
        pass

    @abstractmethod
    def delete_by_template(self, template):
        """

        Deletes all records that match the template.

        :param template: A template.
        :return: A count of the rows deleted.
        """
        pass

    @abstractmethod
    def delete_by_key(self, key_fields):
        """

        Deletes the record that match the key values.

        :param key_fields: List containing the values for the key columns
        :return: A count of the rows deleted.
        """
        pass

    @abstractmethod
    def update_by_template(self, template, new_values):
        """

        :param template: A template that defines which matching rows to update.
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

    @abstractmethod
    def update_by_key(self, key_fields, new_values):
        """

        :param key_fields: List of values for primary key fields
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

In [ ]:
from W4111_F19_HW1.src.BaseDataTable import BaseDataTable
import copy
import csv


class CSVDataTable(BaseDataTable):
    """
    The implementation classes (XXXDataTable) for CSV database, relational, etc. with extend the
    base class and implement the abstract methods.
    """

    def __init__(self, table_name, connect_info, key_columns):
        """

        :param table_name: Logical name of the table.
        :param connect_info: Dictionary of parameters necessary to connect to the data.
        :param key_columns: List, in order, of the columns (fields) that comprise the primary key.
        """
        pass

    def find_by_primary_key(self, key_fields, field_list=None):
        """

        :param key_fields: The list with the values for the key_columns, in order, to use to find a record.
        :param field_list: A subset of the fields of the record to return.
        :return: None, or a dictionary containing the requested fields for the record identified
            by the key.
        """
        pass

    def find_by_template(self, template, field_list=None, limit=None, offset=None, order_by=None):
        """

        :param template: A dictionary of the form { "field1" : value1, "field2": value2, ...}
        :param field_list: A list of request fields of the form, ['fielda', 'fieldb', ...]
        :param limit: Do not worry about this for now.
        :param offset: Do not worry about this for now.
        :param order_by: Do not worry about this for now.
        :return: A list containing dictionaries. A dictionary is in the list representing each record
            that matches the template. The dictionary only contains the requested fields.
        """
        pass

    def delete_by_key(self, key_fields):
        """

        Deletes the record that matches the key.

        :param template: A template.
        :return: A count of the rows deleted.
        """
        pass

    def delete_by_template(self, template):
        """

        :param template: Template to determine rows to delete.
        :return: Number of rows deleted.
        """
        pass

    def update_by_key(self, key_fields, new_values):
        """

        :param key_fields: List of value for the key fields.
        :param new_values: A dict of field:value to set for updated row.
        :return: Number of rows updated.
        """

    def update_by_template(self, template, new_values):
        """

        :param template: Template for rows to match.
        :param new_values: New values to set for matching fields.
        :return: Number of rows updated.
        """
        pass

    def insert(self, new_record):
        """

        :param new_record: A dictionary representing a row to add to the set of records.
        :return: None
        """
        pass

    def get_rows(self):
        return self._rows

In [ ]:
from W4111_F19_HW1.src.BaseDataTable import BaseDataTable
import pymysql

class RDBDataTable(BaseDataTable):

    """
    The implementation classes (XXXDataTable) for CSV database, relational, etc. with extend the
    base class and implement the abstract methods.
    """

    def __init__(self, table_name, connect_info, key_columns):
        """

        :param table_name: Logical name of the table.
        :param connect_info: Dictionary of parameters necessary to connect to the data.
        :param key_columns: List, in order, of the columns (fields) that comprise the primary key.
        """
        pass

    def find_by_primary_key(self, key_fields, field_list=None):
        """

        :param key_fields: The list with the values for the key_columns, in order, to use to find a record.
        :param field_list: A subset of the fields of the record to return.
        :return: None, or a dictionary containing the requested fields for the record identified
            by the key.
        """
        pass

    def find_by_template(self, template, field_list=None, limit=None, offset=None, order_by=None):
        """

        :param template: A dictionary of the form { "field1" : value1, "field2": value2, ...}
        :param field_list: A list of request fields of the form, ['fielda', 'fieldb', ...]
        :param limit: Do not worry about this for now.
        :param offset: Do not worry about this for now.
        :param order_by: Do not worry about this for now.
        :return: A list containing dictionaries. A dictionary is in the list representing each record
            that matches the template. The dictionary only contains the requested fields.
        """
        pass

    def delete_by_key(self, key_fields):
        """

        Deletes the record that matches the key.

        :param template: A template.
        :return: A count of the rows deleted.
        """
        pass

    def delete_by_template(self, template):
        """

        :param template: Template to determine rows to delete.
        :return: Number of rows deleted.
        """
        pass

    def update_by_key(self, key_fields, new_values):
        """

        :param key_fields: List of value for the key fields.
        :param new_values: A dict of field:value to set for updated row.
        :return: Number of rows updated.
        """

    def update_by_template(self, template, new_values):
        """

        :param template: Template for rows to match.
        :param new_values: New values to set for matching fields.
        :return: Number of rows updated.
        """
        pass

    def insert(self, new_record):
        """

        :param new_record: A dictionary representing a row to add to the set of records.
        :return: None
        """
        pass

    def get_rows(self):
        return self._rows

### Implementation Hints

- You have all of the functions you need for the ```RDBDataTable``` except for the ones with keys. We will understand how to do keys in the next lecture, but is extremely simple.


- What about the ```CSVDataTale?``` Well, looking at the ```RDBDataTable,``` the core concept what forming a ```WHERE``` clause.


- How to load the data?

In [99]:
import csv

def load_csv_file(fn):
    result = []
    with open(fn, "r") as in_file:
        csv_file = csv.DictReader(in_file)
        for r in csv_file:
            result.append(r)
            
    return result

In [100]:
file_dir = "C:\\Users\\dferguso\\ansys_one_drive\\Columbia\Projects\\W4111\\HW1Impl\\Data" + \
            "\\baseballdatabank-2019.2\\core\\"   
fn = file_dir + "People" + ".csv"
rows = load_csv_file(fn)

In [101]:
print("No of rows = ", len(rows))

No of rows =  19617

In [104]:
print("First 1o rows = \n", json.dumps(rows[0:9], indent=2))

First 1o rows =
 [
  {
    "playerID": "aardsda01",
    "birthYear": "1981",
    "birthMonth": "12",
    "birthDay": "27",
    "birthCountry": "USA",
    "birthState": "CO",
    "birthCity": "Denver",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "David",
    "nameLast": "Aardsma",
    "nameGiven": "David Allan",
    "weight": "215",
    "height": "75",
    "bats": "R",
    "throws": "R",
    "debut": "2004-04-06",
    "finalGame": "2015-08-23",
    "retroID": "aardd001",
    "bbrefID": "aardsda01"
  },
  {
    "playerID": "aaronha01",
    "birthYear": "1934",
    "birthMonth": "2",
    "birthDay": "5",
    "birthCountry": "USA",
    "birthState": "AL",
    "birthCity": "Mobile",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Hank",
    "nameLast": "Aaron",
    "nameGiven": "Henry Louis",
    "weight": "180",
    "height": "72",
    "bats": "R",
    "throws": "R",
    "debut": "1954-04-13",
    "finalGame": "1976-10-03",
    "retroID": "aaroh101",
    "bbrefID": "aaronha01"
  },
  {
    "playerID": "aaronto01",
    "birthYear": "1939",
    "birthMonth": "8",
    "birthDay": "5",
    "birthCountry": "USA",
    "birthState": "AL",
    "birthCity": "Mobile",
    "deathYear": "1984",
    "deathMonth": "8",
    "deathDay": "16",
    "deathCountry": "USA",
    "deathState": "GA",
    "deathCity": "Atlanta",
    "nameFirst": "Tommie",
    "nameLast": "Aaron",
    "nameGiven": "Tommie Lee",
    "weight": "190",
    "height": "75",
    "bats": "R",
    "throws": "R",
    "debut": "1962-04-10",
    "finalGame": "1971-09-26",
    "retroID": "aarot101",
    "bbrefID": "aaronto01"
  },
  {
    "playerID": "aasedo01",
    "birthYear": "1954",
    "birthMonth": "9",
    "birthDay": "8",
    "birthCountry": "USA",
    "birthState": "CA",
    "birthCity": "Orange",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Don",
    "nameLast": "Aase",
    "nameGiven": "Donald William",
    "weight": "190",
    "height": "75",
    "bats": "R",
    "throws": "R",
    "debut": "1977-07-26",
    "finalGame": "1990-10-03",
    "retroID": "aased001",
    "bbrefID": "aasedo01"
  },
  {
    "playerID": "abadan01",
    "birthYear": "1972",
    "birthMonth": "8",
    "birthDay": "25",
    "birthCountry": "USA",
    "birthState": "FL",
    "birthCity": "Palm Beach",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Andy",
    "nameLast": "Abad",
    "nameGiven": "Fausto Andres",
    "weight": "184",
    "height": "73",
    "bats": "L",
    "throws": "L",
    "debut": "2001-09-10",
    "finalGame": "2006-04-13",
    "retroID": "abada001",
    "bbrefID": "abadan01"
  },
  {
    "playerID": "abadfe01",
    "birthYear": "1985",
    "birthMonth": "12",
    "birthDay": "17",
    "birthCountry": "D.R.",
    "birthState": "La Romana",
    "birthCity": "La Romana",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Fernando",
    "nameLast": "Abad",
    "nameGiven": "Fernando Antonio",
    "weight": "220",
    "height": "73",
    "bats": "L",
    "throws": "L",
    "debut": "2010-07-28",
    "finalGame": "2017-10-01",
    "retroID": "abadf001",
    "bbrefID": "abadfe01"
  },
  {
    "playerID": "abadijo01",
    "birthYear": "1850",
    "birthMonth": "11",
    "birthDay": "4",
    "birthCountry": "USA",
    "birthState": "PA",
    "birthCity": "Philadelphia",
    "deathYear": "1905",
    "deathMonth": "5",
    "deathDay": "17",
    "deathCountry": "USA",
    "deathState": "NJ",
    "deathCity": "Pemberton",
    "nameFirst": "John",
    "nameLast": "Abadie",
    "nameGiven": "John W.",
    "weight": "192",
    "height": "72",
    "bats": "R",
    "throws": "R",
    "debut": "1875-04-26",
    "finalGame": "1875-06-10",
    "retroID": "abadj101",
    "bbrefID": "abadijo01"
  },
  {
    "playerID": "abbated01",
    "birthYear": "1877",
    "birthMonth": "4",
    "birthDay": "15",
    "birthCountry": "USA",
    "birthState": "PA",
    "birthCity": "Latrobe",
    "deathYear": "1957",
    "deathMonth": "1",
    "deathDay": "6",
    "deathCountry": "USA",
    "deathState": "FL",
    "deathCity": "Fort Lauderdale",
    "nameFirst": "Ed",
    "nameLast": "Abbaticchio",
    "nameGiven": "Edward James",
    "weight": "170",
    "height": "71",
    "bats": "R",
    "throws": "R",
    "debut": "1897-09-04",
    "finalGame": "1910-09-15",
    "retroID": "abbae101",
    "bbrefID": "abbated01"
  },
  {
    "playerID": "abbeybe01",
    "birthYear": "1869",
    "birthMonth": "11",
    "birthDay": "11",
    "birthCountry": "USA",
    "birthState": "VT",
    "birthCity": "Essex",
    "deathYear": "1962",
    "deathMonth": "6",
    "deathDay": "11",
    "deathCountry": "USA",
    "deathState": "VT",
    "deathCity": "Colchester",
    "nameFirst": "Bert",
    "nameLast": "Abbey",
    "nameGiven": "Bert Wood",
    "weight": "175",
    "height": "71",
    "bats": "R",
    "throws": "R",
    "debut": "1892-06-14",
    "finalGame": "1896-09-23",
    "retroID": "abbeb101",
    "bbrefID": "abbeybe01"
  }
]

- Well, now that I have some rows? How do I find the ones what match a template?

In [107]:
def matches_template(row, template):
    
    result = True
    if template is not None:
        for k,v in template.items():
            if v != row.get(k, None):
                result = False
                break
                
    return result

In [105]:
row = {
    "playerID": "abadan01",
    "birthYear": "1972",
    "birthMonth": "8",
    "birthDay": "25",
    "birthCountry": "USA",
    "birthState": "FL",
    "birthCity": "Palm Beach",
    "deathYear": "",
    "deathMonth": "",
    "deathDay": "",
    "deathCountry": "",
    "deathState": "",
    "deathCity": "",
    "nameFirst": "Andy",
    "nameLast": "Abad",
    "nameGiven": "Fausto Andres",
    "weight": "184",
    "height": "73",
    "bats": "L",
    "throws": "L",
    "debut": "2001-09-10",
    "finalGame": "2006-04-13",
    "retroID": "abada001",
    "bbrefID": "abadan01"
  }

In [109]:
m1 = matches_template(row, {"birthDay": "25","birthCountry": "USA"})
print("Match = ", m1)

Match =  True

In [110]:
m1 = matches_template(row, {"birthDay": "27","birthCountry": "USA"})
print("Match = ", m1)

Match =  False

- What if I only want a subset of the columns?

In [111]:
def get_columns(row, col_list):
    
    result = {}
    for c in col_list:
        result[c] = row[c]
    return result

In [112]:
cols = get_columns(row, ['playerID', 'nameLast'])
print("The requested columns are = ", cols)

The requested columns are =  {'playerID': 'abadan01', 'nameLast': 'Abad'}

- You have all the building blocks now, and I have given you started code that eliminates the need to do a lot of weird, tricky Python stuff.

### But Wait, There is More!

- The project folder contains CSV files for customers, orders and order_details.


- Implement and test a CSV version of the function:

In [ ]:
def revenue_report_csv(customer_number=None, order_number=None, order_status=None, country=None):
    """
    Returns the orders and total value (sum of value of order items).

    :param customer_number: Customer to get orders for. None gets all.
    :param order_number: Same for order number.
    :param order_status: Same for order status.
    :param country: Same for customer country
    :return: Matching information.
    """
    pass

### How Do I Get Started?

<hr style="height:1px;">

| <img src="../../images/hw1_step_1.jpg" width="900px"> |
| :---: |
| __HW1 Step 1__ |

<hr style="height:1px;">

<br>
<div style="color:red;font-size:32px;line-height: 120%;">
    My homework assignments are incompletely specified compared to homework assignments you receive in other courses.
    <ul>
        <span style="font-size: 28px"><li>In the real world, specifications for what you must implement are incredibly incomplete and often contradictory/unclear. </li>
        <span style="font-size: 28px"><li>Figuring out how to translate high-level requests into concrete implementations is what computer scientists, data engineers, etc. do for a living. This is our intellectual value.</li></span>
            </ul>
        This will be frustrating and challenging. I understand this and am <b><u><i>very lenient </i></u></b> on grading. I will  spend time helping you figure things out.
<div>

1. This homework is due in 2 weeks.<br><br>
2. I need to teach you a few more things next week before you can complete the homework.<br><br>
2. You have learned enough to get started and solve all of the hard problems.
    - Open and loading files.
    - Connecting to databases.
    - Matching rows to templates.<br><br>
3. __All of the other methods are simple additions to the above.__<br><br>